package com.zoutrankil.questdbwithdata.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_backtest_daily`; source snapshot 2026-09-28. */
public record BacktestDailyView(
        Instant tradeDate,
        String tsCode,
        Double open,
        Double high,
        Double low,
        Double close,
        Double vol,
        Double amount,
        Double adjFactor,
        Double upLimit,
        Double downLimit,
        Long isSuspended,
        Integer isSt) {}
