package com.zoutrankil.questdbwithdata.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_macro_core_monthly`; source snapshot 2026-09-28. */
public record MacroCoreMonthlyView(
        Instant month,
        Double cpiYoy,
        Double ppiYoy,
        Double pmiMfg,
        Double gdpYoy,
        Double m2Yoy,
        Double socialFinancingStock,
        Double newRmbLoan,
        Double socialFinancingYoy) {}
