package com.zoutrankil.questdbwithdata.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_regime_market_monthly`; source snapshot 2026-09-28. */
public record RegimeMarketMonthlyView(
        Instant month,
        Double northboundNetBuy1m,
        Double marginBalanceMonthEnd,
        Double marginBalanceChange1m,
        Double allAPeTtmMedian,
        Double allAPbMedian,
        Double allAPeTtmPercentile,
        Double allAPbPercentile,
        Double erp) {}
