package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `backtest_daily`; source snapshot 2026-09-28. */
public record BacktestDailyRow(
        Instant tradeDate,
        String tsCode,
        Double open,
        Double high,
        Double low,
        Double close,
        Double vol,
        Double amount,
        Double adjFactor,
        Double upLimit,
        Double downLimit,
        Integer isSuspended,
        Integer isSt) {}
