package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `block_trade`; source snapshot 2026-09-28. */
public record BlockTradeRow(
        String tsCode,
        Instant tradeDate,
        Double price,
        Double vol,
        Double amount,
        String buyer,
        String seller) {}
