package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `broker_statement_deliveries`; source snapshot 2026-09-28. */
public record BrokerStatementDeliveriesRow(
        String sourceKey,
        String brokerName,
        String accountId,
        String clientNo,
        String businessDate,
        String eventTime,
        Instant eventAt,
        String serialNo,
        String securityCode,
        String tsCode,
        String securityName,
        String businessFlag,
        String side,
        Double quantity,
        Double price,
        Double tradeAmount,
        Double netCommission,
        Double stampDuty,
        Double transferFee,
        Double regulatoryFee,
        Double handlingFee,
        Double otherFee,
        Double securityFee,
        Double clearingAmount,
        Double postCashBalance,
        Double postSecurityBalance,
        String currency,
        String orderId,
        Double accruedInterest,
        Integer sourcePage,
        String sourceFile,
        String sourceSha256,
        String statementPeriod,
        Instant importedAt,
        String sourceSection) {}
