package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `broker_recommend`; source snapshot 2026-09-28. */
public record BrokerRecommendRow(
        Instant month,
        String broker,
        String tsCode,
        String name) {}
