package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `broker_statement_cashflows`; source snapshot 2026-09-28. */
public record BrokerStatementCashflowsRow(
        String sourceKey,
        String brokerName,
        String accountId,
        String clientNo,
        String businessDate,
        String eventTime,
        Instant eventAt,
        String serialNo,
        String market,
        String currency,
        String transactionType,
        Double amount,
        Double postBalance,
        String remark,
        Integer sourcePage,
        String sourceFile,
        String sourceSha256,
        String statementPeriod,
        Instant importedAt) {}
