package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cn_gdp`; source snapshot 2026-09-28. */
public record CnGdpRow(
        String quarter,
        Instant reportDate,
        Double gdp,
        Double gdpYoy,
        Double pi,
        Double piYoy,
        Double si,
        Double siYoy,
        Double ti,
        Double tiYoy) {}
