package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cn_m`; source snapshot 2026-09-28. */
public record CnMRow(
        Instant month,
        Double m0,
        Double m0Yoy,
        Double m0Mom,
        Double m1,
        Double m1Yoy,
        Double m1Mom,
        Double m2,
        Double m2Yoy,
        Double m2Mom) {}
