package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cn_ppi`; source snapshot 2026-09-28. */
public record CnPpiRow(
        Instant month,
        Double ppiYoy,
        Double ppiMpYoy,
        Double ppiMpQmYoy,
        Double ppiMpRmYoy,
        Double ppiMpPYoy,
        Double ppiCgYoy,
        Double ppiCgFYoy,
        Double ppiCgCYoy,
        Double ppiCgAduYoy,
        Double ppiCgDcgYoy,
        Double ppiMom,
        Double ppiMpMom,
        Double ppiMpQmMom,
        Double ppiMpRmMom,
        Double ppiMpPMom,
        Double ppiCgMom,
        Double ppiCgFMom,
        Double ppiCgCMom,
        Double ppiCgAduMom,
        Double ppiCgDcgMom,
        Double ppiAccu,
        Double ppiMpAccu,
        Double ppiMpQmAccu,
        Double ppiMpRmAccu,
        Double ppiMpPAccu,
        Double ppiCgAccu,
        Double ppiCgFAccu,
        Double ppiCgCAccu,
        Double ppiCgAduAccu,
        Double ppiCgDcgAccu) {}
