package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `company_intrinsic_valuation_consensus`; source snapshot 2026-09-28. */
public record CompanyIntrinsicValuationConsensusRow(
        Instant valuationDate,
        String tsCode,
        String name,
        String industryL2,
        String routeId,
        Double marketPrice,
        Double totalMv,
        Double peTtm,
        Double pb,
        Double fairValueLow,
        Double fairValueBase,
        Double fairValueHigh,
        Double upsideLow,
        Double upsideBase,
        Double upsideHigh,
        Integer configuredModels,
        Integer calculatedModels,
        Double eligibleModelWeight,
        Double consensusConfidence,
        Double modelDispersion,
        String consensusStatus,
        String routeVersion,
        String assumptionVersion,
        String runId) {}
