package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `company_intrinsic_valuation_model`; source snapshot 2026-09-28. */
public record CompanyIntrinsicValuationModelRow(
        Instant valuationDate,
        String tsCode,
        String name,
        String industryL2,
        String routeId,
        String modelId,
        String eligibilityStatus,
        String eligibilityReason,
        Double marketPrice,
        Double fairValueLow,
        Double fairValueBase,
        Double fairValueHigh,
        Double upsideLow,
        Double upsideBase,
        Double upsideHigh,
        Double modelConfidence,
        Double modelWeightConfig,
        Double explicitGrowthBase,
        Double terminalGrowthBase,
        Double costOfEquity,
        Double wacc,
        Double riskFreeRate,
        Double beta,
        Double betaObservations,
        Instant reportEndDate,
        Instant reportAnnDate,
        String routeVersion,
        String assumptionVersion,
        String runId) {}
