package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `daily`; source snapshot 2026-09-28. */
public record DailyRow(
        String tsCode,
        Instant tradeDate,
        Double open,
        Double high,
        Double low,
        Double close,
        Double preClose,
        Double change,
        Double pctChg,
        Double vol,
        Double amount,
        Double ahVol,
        Double ahAmount) {}
