package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `dividend`; source snapshot 2026-09-28. */
public record DividendRow(
        String tsCode,
        String endDate,
        Instant annDate,
        String divProc,
        Double stkDiv,
        Double stkBoRate,
        Double stkCoRate,
        Double cashDiv,
        Double cashDivTax,
        String recordDate,
        String exDate,
        String payDate,
        String divListdate,
        String impAnnDate,
        String baseDate,
        Double baseShare,
        Instant updateTime) {}
