package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `eco_cal`; source snapshot 2026-09-28. */
public record EcoCalRow(
        Instant date,
        String time,
        String currency,
        String country,
        String event,
        String value,
        String preValue,
        String foreValue) {}
