package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `etf_basic`; source snapshot 2026-09-28. */
public record EtfBasicRow(
        String tsCode,
        String name,
        String management,
        String custodian,
        String fundType,
        String foundDate,
        String dueDate,
        String listDate,
        String issueDate,
        String delistDate,
        Double issueAmount,
        Double mFee,
        Double cFee,
        Double durationYear,
        Double pValue,
        Double minAmount,
        Double expReturn,
        String benchmark,
        String status,
        String investType,
        String type,
        String trustee,
        String purcStartdate,
        String redmStartdate,
        String market,
        Instant timestamp,
        Instant updateTime) {}
