package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `etf_daily`; source snapshot 2026-09-28. */
public record EtfDailyRow(
        String tsCode,
        Instant timestamp,
        Double preClose,
        Double open,
        Double high,
        Double low,
        Double close,
        Double change,
        Double pctChg,
        Double vol,
        Double amount) {}
