package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `etf_portfolio`; source snapshot 2026-09-28. */
public record EtfPortfolioRow(
        String tsCode,
        Instant annDate,
        Instant endDate,
        String symbol,
        Double mkv,
        Double amount,
        Double stkMkvRatio,
        Double stkFloatRatio,
        Instant updateTime) {}
