package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `express`; source snapshot 2026-09-28. */
public record ExpressRow(
        String tsCode,
        Instant annDate,
        String endDate,
        Double revenue,
        Double operateProfit,
        Double totalProfit,
        Double nIncome,
        Double totalAssets,
        Double totalHldrEqyExcMinInt,
        Double dilutedEps,
        Double dilutedRoe,
        Double yoyNetProfit,
        Double bps,
        Double yoySales,
        Double yoyOp,
        Double yoyTp,
        Double yoyDeduNp,
        Double yoyEps,
        Double yoyRoe,
        Double growthAssets,
        Double yoyEquity,
        Double growthBps,
        Double openNetAssets,
        Double openBps,
        Double orLastYear,
        Double opLastYear,
        Double tpLastYear,
        Double npLastYear,
        Double epsLastYear,
        String perfSummary,
        Integer isAudit,
        String remark) {}
