package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_usage`; source snapshot 2026-09-28. */
public record FactorUsageRow(
        Instant observedAt,
        String factorId,
        String definitionVersion,
        String consumerType,
        String consumerId,
        String usageRole,
        String lifecycleStatus,
        String runId) {}
