package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_monitor_daily`; source snapshot 2026-09-28. */
public record FactorMonitorDailyRow(
        Instant signalDate,
        Instant maturityDate,
        String factorId,
        String definitionVersion,
        String universeId,
        String horizon,
        String directionPrior,
        String effectiveDirection,
        Double rankIc,
        Double rankIcPValue,
        Integer sampleCount,
        Integer universeCount,
        Double coverage,
        Double group1Return,
        Double group2Return,
        Double group3Return,
        Double group4Return,
        Double group5Return,
        Double topMinusBottomReturn,
        Double orientedTopMinusBottomReturn,
        Double monotonicityScore,
        Double factorAutocorr,
        String dataQualityStatus,
        String runId,
        Instant computedAt) {}
