package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_regime_daily`; source snapshot 2026-09-28. */
public record FactorRegimeDailyRow(
        Instant tradeDate,
        String factorId,
        String universeId,
        String definitionVersion,
        String horizon,
        String regimeState,
        Double effectiveWeight,
        Double meanIc20,
        Double meanIc40,
        Double meanIc60,
        Double positiveRatio20,
        Double topMinusBottom20,
        String runId) {}
