package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fina_mainbz`; source snapshot 2026-09-28. */
public record FinaMainbzRow(
        String tsCode,
        Instant endDate,
        String bzItem,
        Double bzSales,
        Double bzProfit,
        Double bzCost,
        String currType,
        String updateFlag,
        String bzCode) {}
