package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `forecast`; source snapshot 2026-09-28. */
public record ForecastRow(
        String tsCode,
        Instant annDate,
        String endDate,
        String type,
        Double pChangeMin,
        Double pChangeMax,
        Double netProfitMin,
        Double netProfitMax,
        Double lastParentNet,
        String firstAnnDate,
        String summary,
        String changeReason) {}
