package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_basic`; source snapshot 2026-09-28. */
public record FutBasicRow(
        String tsCode,
        String symbol,
        String exchange,
        String name,
        String futCode,
        Double multiplier,
        String tradeUnit,
        Double perUnit,
        String quoteUnit,
        String listDate,
        String delistDate,
        String dMonth,
        String lastDdate,
        String tradeTimeDesc,
        Instant timestamp,
        Instant updateTime) {}
