package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_daily`; source snapshot 2026-09-28. */
public record FutDailyRow(
        String tsCode,
        Instant tradeDate,
        Double preClose,
        Double preSettle,
        Double open,
        Double high,
        Double low,
        Double close,
        Double settle,
        Double change1,
        Double change2,
        Double vol,
        Double amount,
        Double oi,
        Double oiChg,
        Double delvSettle,
        Instant updateTime) {}
