package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_holding`; source snapshot 2026-09-28. */
public record FutHoldingRow(
        Instant tradeDate,
        String symbol,
        String broker,
        Long vol,
        Long volChg,
        Long longHld,
        Long longChg,
        Long shortHld,
        Long shortChg,
        String exchange,
        Instant updateTime) {}
