package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_settle`; source snapshot 2026-09-28. */
public record FutSettleRow(
        String tsCode,
        Instant tradeDate,
        Double settle,
        Double tradingFeeRate,
        Double tradingFee,
        Double deliveryFee,
        Double bHedgingMarginRate,
        Double sHedgingMarginRate,
        Double longMarginRate,
        Double shortMarginRate,
        Double offsetTodayFee,
        String exchange,
        Instant updateTime) {}
