package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `income_period_meta`; source snapshot 2026-09-28. */
public record IncomePeriodMetaRow(
        String period,
        Instant lastFetchedAt,
        Integer rowCount) {}
