package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index`; source snapshot 2026-09-28. */
public record IndexRow(
        String indexCode,
        String indexShortName,
        String indexFullName,
        String baseDate,
        Double basePoint,
        String indexSeries,
        Double sampleCount,
        Double latestClose,
        Double return1m,
        String assetClass,
        String indexHotspot,
        String currency,
        String isCooperation,
        String hasTrackingProduct,
        String complianceStatus,
        String indexCategory,
        String publishDate,
        Instant importTime) {}
