package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index_monthly`; source snapshot 2026-09-28. */
public record IndexMonthlyRow(
        String tsCode,
        Instant tradeDate,
        Double close,
        Double open,
        Double high,
        Double low,
        Double preClose,
        Double change,
        Double pctChg,
        Double vol,
        Double amount,
        String layer,
        String bucket,
        Instant updateTime) {}
