package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index_daily_basic`; source snapshot 2026-09-28. */
public record IndexDailyBasicRow(
        String tsCode,
        Instant tradeDate,
        Double totalMv,
        Double floatMv,
        Double totalShare,
        Double floatShare,
        Double freeShare,
        Double turnoverRate,
        Double turnoverRateF,
        Double pe,
        Double peTtm,
        Double pb) {}
