package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `industry_valuation_membership_conflict`; source snapshot 2026-09-28. */
public record IndustryValuationMembershipConflictRow(
        Instant valuationDate,
        String tsCode,
        Integer activeIndustries,
        String routeVersion,
        String runId) {}
