package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `industry_valuation_route_assignment`; source snapshot 2026-09-28. */
public record IndustryValuationRouteAssignmentRow(
        Instant effectiveFrom,
        String industryL2,
        String routeId,
        String forecastStyle,
        String modelId,
        Double modelWeight,
        String routeVersion,
        String assumptionVersion,
        String runId) {}
