package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `industry_valuation_materialization_run`; source snapshot 2026-09-28. */
public record IndustryValuationMaterializationRunRow(
        Instant createdAt,
        String runId,
        String status,
        Instant startDate,
        Instant endDate,
        String productId,
        String packageId,
        String inputDigest,
        String schemaDigest,
        String routeVersion,
        String assumptionVersion,
        Long modelRows,
        Long consensusRows,
        Long industryRows,
        Long conflictRows) {}
