package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `l2_live_subscription_intents`; source snapshot 2026-09-28. */
public record L2LiveSubscriptionIntentsRow(
        String symbol,
        String channel,
        Integer priority,
        String source,
        String reason,
        Boolean enabled,
        Instant expiresAt,
        Instant updatedAt) {}
