package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `l2_live_subscription_events`; source snapshot 2026-09-28. */
public record L2LiveSubscriptionEventsRow(
        String topic,
        String symbol,
        String channel,
        String action,
        String status,
        Integer mid,
        String error,
        Instant updatedAt) {}
