package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `l2_live_gateway_stats`; source snapshot 2026-09-28. */
public record L2LiveGatewayStatsRow(
        String actorId,
        String connectionState,
        Integer activeSymbols,
        Integer activeTopics,
        Integer queueSize,
        Long totalReceived,
        Long totalProcessed,
        Long parseErrors,
        Long failedCount,
        Instant lastReceiveTime,
        Instant lastProcessedTime,
        String channelCounts,
        String phaseCounts,
        String logPath,
        String rawRoot,
        Instant updatedAt) {}
