package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `margin_secs`; source snapshot 2026-09-28. */
public record MarginSecsRow(
        Instant tradeDate,
        String tsCode,
        String name,
        String exchange) {}
