package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `margin_zrz`; source snapshot 2026-09-28. */
public record MarginZrzRow(
        Instant tradeDate,
        Double ob,
        Double aucAmount,
        Double repoAmount,
        Double repayAmount,
        Double cb) {}
