package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `moneyflow_ths`; source snapshot 2026-09-28. */
public record MoneyflowThsRow(
        String tsCode,
        Instant tradeDate,
        String name,
        Double pctChange,
        Double latest,
        Double netAmount,
        Double netD5Amount,
        Double buyLgAmount,
        Double buyLgAmountRate,
        Double buyMdAmount,
        Double buyMdAmountRate,
        Double buySmAmount,
        Double buySmAmountRate) {}
