package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `moneyflow`; source snapshot 2026-09-28. */
public record MoneyflowRow(
        String tsCode,
        Instant tradeDate,
        Long buySmVol,
        Double buySmAmount,
        Long sellSmVol,
        Double sellSmAmount,
        Long buyMdVol,
        Double buyMdAmount,
        Long sellMdVol,
        Double sellMdAmount,
        Long buyLgVol,
        Double buyLgAmount,
        Long sellLgVol,
        Double sellLgAmount,
        Long buyElgVol,
        Double buyElgAmount,
        Long sellElgVol,
        Double sellElgAmount,
        Long netMfVol,
        Double netMfAmount) {}
