package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `order_fills`; source snapshot 2026-09-28. */
public record OrderFillsRow(
        String fillId,
        String orderId,
        Double fillPrice,
        Integer fillQuantity,
        Instant fillTime,
        Double fillAmount,
        Double commission,
        Boolean isMaker) {}
