package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `orders`; source snapshot 2026-09-28. */
public record OrdersRow(
        String orderId,
        String signalId,
        String parentOrderId,
        String tsCode,
        String side,
        String orderType,
        String priceType,
        Long quantity,
        Double price,
        String status,
        Long filledQuantity,
        Double filledAmount,
        Double avgPrice,
        Double commission,
        Double slippage,
        Instant createTime,
        Instant submitTime,
        Instant fillTime,
        Instant cancelTime,
        String executionMode,
        String brokerOrderId,
        String strategyName,
        String orderRemark,
        String riskCheckResult,
        String rejectReason) {}
