package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `paired_execution_plans`; source snapshot 2026-09-28. */
public record PairedExecutionPlansRow(
        String planId,
        String strategyId,
        String instanceId,
        String accountKey,
        String signalDate,
        String status,
        String reviewMode,
        String reviewedBy,
        String regime,
        Double regimeScore,
        String reasonCodes,
        String executionStyle,
        String oldBasket,
        String newBasket,
        String spreadSnapshot,
        String riskLimits,
        String legs,
        String signalIds,
        String auditReason,
        Double expectedDayPnl,
        Double expectedShortfall,
        String simulationSummary,
        String t0Overlay,
        Instant createdAt,
        Instant updatedAt) {}
