package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `pledge_stat`; source snapshot 2026-09-28. */
public record PledgeStatRow(
        String tsCode,
        Instant endDate,
        Long pledgeCount,
        Double unrestPledge,
        Double restPledge,
        Double totalShare,
        Double pledgeRatio) {}
