package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `prediction_definition_v1`; source snapshot 2026-09-28. */
public record PredictionDefinitionV1Row(
        Instant registeredAt,
        String predictionId,
        String definitionVersion,
        String nameZh,
        String nameEn,
        String descriptionZh,
        String entityType,
        String frequency,
        String horizon,
        String outputKind,
        String modelId,
        String modelVersion,
        String lifecycleStatus,
        String owner,
        String factorDependencies,
        String usedBy,
        Boolean enabled) {}
