package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_orders`; source snapshot 2026-09-28. */
public record QmtOrdersRow(
        String brokerOrderId,
        String tsCode,
        String side,
        Integer quantity,
        Double price,
        Integer filledQuantity,
        Double filledAmount,
        String status,
        String statusName,
        Instant orderTime,
        String strategyName,
        String orderRemark,
        String stockName,
        String accountId,
        Instant queryTime,
        String brokerName) {}
