package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_trades`; source snapshot 2026-09-28. */
public record QmtTradesRow(
        String tradeId,
        String brokerOrderId,
        String tsCode,
        String side,
        Double price,
        Integer quantity,
        Double amount,
        Instant tradeTime,
        Double commission,
        String stockName,
        String accountId,
        Instant queryTime,
        String brokerName) {}
