package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `regime_margin_leverage_daily`; source snapshot 2026-09-28. */
public record RegimeMarginLeverageDailyRow(
        Instant tradeDate,
        Double marginBalance,
        Double freeFloatMarketCap,
        Double marginRatio,
        Double aggregateMarginBalance,
        Double detailMarginBalance,
        Double reconciliationGapRatio,
        String sourceMode,
        Boolean fallbackUsed,
        String exchangeCoverage,
        Integer duplicateRowsDropped,
        Integer conflictingExchangeCount,
        Integer marketCapSecurityCount,
        String qualityStatus,
        String reasonCode,
        String reasonMessage,
        String methodVersion,
        String sourceLineage,
        String inputFingerprint,
        String runId,
        Instant computedAt) {}
