package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `repurchase`; source snapshot 2026-09-28. */
public record RepurchaseRow(
        String tsCode,
        Instant annDate,
        String endDate,
        String proc,
        String expDate,
        Double vol,
        Double amount,
        Double highLimit,
        Double lowLimit) {}
