package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `retail_sentiment_daily_cache`; source snapshot 2026-09-28. */
public record RetailSentimentDailyCacheRow(
        Instant tradeDate,
        Double avgRetailRatio,
        Double avgRetailEntropy,
        Double totalRetailAmountYi,
        Double totalRetailNetInflowYi,
        Double avgRelAggro,
        Long totalQ1,
        Long totalQ3,
        Double avgWashTradeRatio,
        Long totalSpoofCount,
        Long totalManipulationCount,
        Double avgMfiScore,
        Double totalMainNetYi,
        String sourceVersion) {}
