package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `rmb_index_daily`; source snapshot 2026-09-28. */
public record RmbIndexDailyRow(
        Instant tradeDate,
        Double usdPerCny,
        Double eurPerCny,
        Double jpyPerCny,
        Double gbpPerCny,
        Double rmbIndex,
        String source) {}
