package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `sf_month`; source snapshot 2026-09-28. */
public record SfMonthRow(
        Instant month,
        Double incMonth,
        Double incCumval,
        Double stkEndval) {}
