package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `sge_daily`; source snapshot 2026-09-28. */
public record SgeDailyRow(
        String tsCode,
        Instant tradeDate,
        Double close,
        Double open,
        Double high,
        Double low,
        Double priceAvg,
        Double change,
        Double pctChange,
        Double vol,
        Double amount,
        Double oi,
        Double settleVol,
        String settleDire) {}
