package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stk_st_daily`; source snapshot 2026-09-28. */
public record StkStDailyRow(
        String tsCode,
        Integer isSt,
        Instant timestamp) {}
