package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stock_detail_info`; source snapshot 2026-09-28. */
public record StockDetailInfoRow(
        String tsCode,
        Instant updateTime,
        String symbol,
        String name,
        String market,
        String exchange,
        String listStatus,
        String listDate,
        String fullname,
        String enname,
        String cnspell,
        String area,
        String industry,
        String currType,
        String delistDate,
        String isHs,
        String actName,
        String actEntType) {}
