package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_equity_daily`; source snapshot 2026-09-28. */
public record StrategyProductionEquityDailyRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        Double startEquity,
        Double endEquity,
        Double grossReturn,
        Double netReturn,
        Double grossPnl,
        Double commission,
        Double stampTax,
        Double managementFee,
        Double cost,
        Double tradeValue,
        Double turnoverWeight,
        Double buyValue,
        Double sellValue,
        Integer tradeCount,
        Integer stockTradeCount,
        Integer etfTradeCount,
        Integer selectedStCount,
        String rebalanceTrigger,
        Integer holdings,
        Double stockWeight,
        Double etfWeight,
        Double cashWeight,
        String regime,
        Instant createdAt) {}
