package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_target_positions`; source snapshot 2026-09-28. */
public record StrategyTargetPositionsRow(
        String runId,
        String strategyId,
        String instanceId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        Double targetWeight,
        Double targetAmount,
        Double signalPrice,
        Double executionPrice,
        Double valuationPrice,
        String selectedReason,
        String rebalanceTrigger,
        String name) {}
