package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_runs`; source snapshot 2026-09-28. */
public record StrategyProductionRunsRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        String dailyRunId,
        String artifactManifestId,
        String factorPlatformRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String status,
        String rebalanceTrigger,
        Double startEquity,
        Double endEquity,
        Double grossReturn,
        Double netReturn,
        Double stockWeight,
        Double etfWeight,
        Double cashWeight,
        Double cost,
        Integer tradeCount,
        Integer targetCount,
        Integer orderCount,
        String artifactDir,
        String summaryPath,
        String notes,
        Instant createdAt,
        Instant persistedAt) {}
