package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_pnl_attribution_daily`; source snapshot 2026-09-28. */
public record StrategyProductionPnlAttributionDailyRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        String name,
        Double targetWeight,
        Double executionPrice,
        Double valuationPrice,
        Double positionReturn,
        Double grossReturnContribution,
        Double grossPnlContribution,
        Double tradeCost,
        Double managementFeeAlloc,
        Double netPnlApprox,
        Double etfScore,
        Double componentL2ScoreSmooth,
        Double componentBuyBreadthSmooth,
        String portfolioState,
        String stateTriggerReason,
        Double currentDrawdown,
        Instant createdAt) {}
