package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_backtest_runs`; source snapshot 2026-09-28. */
public record StrategyBacktestRunsRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String backtestId,
        String artifactDir,
        String paramsHash,
        String codeVersion,
        Instant startDate,
        Instant endDate,
        Instant dataAsof,
        Double initialCapital,
        Double finalEquity,
        Double totalReturn,
        Double annualizedReturn,
        Double annualizedVol,
        Double sharpe,
        Double maxDrawdown,
        Double winRate,
        Double avgDailyTurnover,
        Double totalTradeValue,
        Double totalCommission,
        Double totalStampTax,
        Double totalManagementFee,
        Double totalCost,
        Integer tradeCount,
        Double avgStockWeight,
        Double avgEtfWeight,
        Double avgCashWeight,
        String notes,
        Instant createdAt) {}
