package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_orders`; source snapshot 2026-09-28. */
public record StrategyProductionOrdersRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        String side,
        Double weightDelta,
        Double tradeValue,
        Double commission,
        Double stampTax,
        Double cost,
        Instant createdAt,
        String name) {}
