package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_instances`; source snapshot 2026-09-28. */
public record StrategyInstancesRow(
        String instanceId,
        String strategyCodeId,
        String name,
        String category,
        String tags,
        String status,
        String params,
        String notes,
        String version,
        String runtimeState,
        String lastResult,
        Instant createdAt,
        Instant updatedAt) {}
