package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_positions`; source snapshot 2026-09-28. */
public record StrategyProductionPositionsRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        String name,
        Double targetWeight,
        Double targetAmount,
        Double price,
        Double signalPrice,
        Double executionPrice,
        Double valuationPrice,
        Instant entryDate,
        Double entryPrice,
        Double etfScore,
        Double componentL2ScoreSmooth,
        Double componentBuyBreadthSmooth,
        Double top3WeightConcentration,
        Double top10LimitTouchWeight,
        Boolean selfOverheatFlag,
        Boolean componentCrowdingFlag,
        Double selectionScore,
        String selectedReason,
        String rebalanceTrigger,
        String etfCategory,
        String broadFamily,
        Instant createdAt) {}
