package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_run_artifact_manifest`; source snapshot 2026-09-28. */
public record StrategyRunArtifactManifestRow(
        String artifactManifestId,
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String artifactPath,
        String relativePath,
        String artifactKind,
        String artifactRole,
        String fileExt,
        Long bytes,
        Long rows,
        Instant minDate,
        Instant maxDate,
        Instant mtime,
        String contentHash,
        Boolean isCache,
        Boolean isStructured,
        String structuredTable,
        Long structuredRows,
        Instant createdAt) {}
