package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_backtest_positions`; source snapshot 2026-09-28. */
public record StrategyBacktestPositionsRow(
        String runId,
        String strategyId,
        String instanceId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        Double targetWeight,
        Double price,
        Double signalPrice,
        Double executionPrice,
        Double valuationPrice,
        Instant entryDate,
        Double entryPrice,
        String regime,
        String etfCategory,
        String broadFamily,
        String selectedReason,
        String rebalanceTrigger) {}
