package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_daily_runs`; source snapshot 2026-09-28. */
public record StrategyDailyRunsRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String status,
        String rebalanceTrigger,
        Double startEquity,
        Double endEquity,
        Double stockWeight,
        Double etfWeight,
        Double cashWeight,
        Double cost,
        Integer tradeCount,
        Integer selectedStCount,
        String artifactDir,
        String summaryPath,
        Instant createdAt) {}
