package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `ths_index`; source snapshot 2026-09-28. */
public record ThsIndexRow(
        String tsCode,
        String name,
        Integer count,
        String exchange,
        String listDate,
        String type,
        Instant updateTime) {}
