package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `tracked_symbols`; source snapshot 2026-09-28. */
public record TrackedSymbolsRow(
        String tsCode,
        Boolean positionActive,
        Integer positionVolume,
        Integer availableVolume,
        Boolean focus1m,
        Boolean focusTick,
        Boolean tMode,
        Integer priority,
        String source,
        String reason,
        Instant expiresAt,
        Instant updatedAt,
        String metadata) {}
