package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `trade_records`; source snapshot 2026-09-28. */
public record TradeRecordsRow(
        String tradeId,
        String tsCode,
        String symbol,
        String stockName,
        String tradeDate,
        String tradeTime,
        String tradeType,
        Double tradePrice,
        Integer tradeVolume,
        Double tradeAmount,
        Double commission,
        Double stampDuty,
        Double transferFee,
        Double totalFee,
        String strategyName,
        String portfolioName,
        String note,
        Instant createTime,
        Instant updateTime,
        String orderId,
        String brokerOrderId,
        String signalId) {}
