package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `trade_signals`; source snapshot 2026-09-28. */
public record TradeSignalsRow(
        String signalId,
        String tsCode,
        String signalType,
        String signalSource,
        Instant signalTime,
        Double signalPrice,
        Double targetPrice,
        Double stopLoss,
        Integer quantity,
        Double confidence,
        String status,
        String reason,
        String orderId,
        Instant updatedAt,
        String updatedBy,
        String reviewedBy,
        String statusNote) {}
