package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `us_tbr`; source snapshot 2026-09-28. */
public record UsTbrRow(
        Instant date,
        Double w4Bd,
        Double w4Ce,
        Double w8Bd,
        Double w8Ce,
        Double w13Bd,
        Double w13Ce,
        Double w17Bd,
        Double w17Ce,
        Double w26Bd,
        Double w26Ce,
        Double w52Bd,
        Double w52Ce) {}
