package com.zoutrankil.questdbwithdata.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `us_tltr`; source snapshot 2026-09-28. */
public record UsTltrRow(
        Instant date,
        Double ltc,
        Double cmt,
        Double eFactor) {}
