package com.zoutrankil.data.domain.table;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cashflow_period_meta`; source snapshot 2026-09-28. */
public record CashflowPeriodMetaRow(
        String period,
        String lastFetchedAt,
        Integer rowCount) {}
