package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cn_cpi`; source snapshot 2026-09-28. */
public record CnCpiRow(
        Instant month,
        Double ntVal,
        Double ntYoy,
        Double ntMom,
        Double ntAccu,
        Double townVal,
        Double townYoy,
        Double townMom,
        Double townAccu,
        Double cntVal,
        Double cntYoy,
        Double cntMom,
        Double cntAccu) {}
