package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `daily_stock_analysis`; source snapshot 2026-09-28. */
public record DailyStockAnalysisRow(
        String tsCode,
        Instant analysisDate,
        String content,
        String modelName,
        Instant updatedAt) {}
