package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `etf_market_overview_daily_cache`; source snapshot 2026-09-28. */
public record EtfMarketOverviewDailyCacheRow(
        Instant tradeDate,
        Long etfCount,
        Double totalShare,
        Double totalSizeYi,
        String sourceVersion) {}
