package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `exchange_calendar`; source snapshot 2026-09-28. */
public record ExchangeCalendarRow(
        String exchange,
        Instant calDate,
        Integer isOpen,
        String pretradeDate) {}
