package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_corr_snapshot`; source snapshot 2026-09-28. */
public record FactorCorrSnapshotRow(
        Instant snapshotDate,
        String factorId1,
        String factorId2,
        String definitionVersion,
        String universeId,
        Double rankCorr,
        String corrCluster,
        String runId) {}
