package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_validation_daily`; source snapshot 2026-09-28. */
public record FactorValidationDailyRow(
        Instant tradeDate,
        String factorId,
        String universeId,
        String definitionVersion,
        String validationProfile,
        String metricName,
        Double metricValue,
        Double threshold,
        String status,
        Integer sampleCount,
        String runId) {}
