package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_observation`; source snapshot 2026-09-28. */
public record FactorObservationRow(
        Instant signalDate,
        String entityType,
        String entityId,
        String factorId,
        String definitionVersion,
        Double factorValue,
        Instant availableAt,
        String qualityStatus,
        String scope,
        String l2SourceLineageDigest) {}
