package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_index_signal_daily`; source snapshot 2026-09-28. */
public record FutIndexSignalDailyRow(
        Instant tradeDate,
        String futCode,
        String mainTsCode,
        String mappingTsCode,
        Double basisPoints,
        Double basisPct,
        Double annualizedBasisPct,
        Double futRet1d,
        Double spotRet1d,
        Double leadSpreadRet,
        String oiState,
        String volumeOiState,
        Double top20Long,
        Double top20Short,
        Double top20Net,
        Double top20NetChg,
        Double signalBasis,
        Double signalPosition,
        Double signalStructure,
        Double signalStrength,
        String dataQualityFlag,
        Instant updatedAt) {}
