package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index_member`; source snapshot 2026-09-28. */
public record IndexMemberRow(
        String indexCode,
        String tsCode,
        Instant updateTime,
        String indexName,
        String conCode,
        String conName,
        String inDate,
        String outDate,
        String isNew,
        Double weight,
        String level,
        String l1Name,
        String l2Name,
        String l3Name) {}
