package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index_daily_market`; source snapshot 2026-09-28. */
public record IndexDailyMarketRow(
        String tsCode,
        Instant tradeDate,
        Double close,
        Double open,
        Double high,
        Double low,
        Double preClose,
        Double change,
        Double pctChg,
        Double vol,
        Double amount,
        Instant updateTime) {}
