package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `margin_all`; source snapshot 2026-09-28. */
public record MarginAllRow(
        Instant tradeDate,
        String exchangeId,
        Double rzye,
        Double rzmre,
        Double rzche,
        Double rqye,
        Double rqmcl,
        Double rzrqye,
        Double rqyl) {}
