package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `market_breadth_daily_cache`; source snapshot 2026-09-28. */
public record MarketBreadthDailyCacheRow(
        Instant tradeDate,
        Long stockCount,
        Long upCount,
        Long downCount,
        Long flatCount,
        Double avgPctChange,
        Double totalAmountYi,
        String sourceVersion) {}
