package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `moneyflow_dc`; source snapshot 2026-09-28. */
public record MoneyflowDcRow(
        String tsCode,
        Instant tradeDate,
        String name,
        Double pctChange,
        Double close,
        Double netAmount,
        Double netAmountRate,
        Double buyElgAmount,
        Double buyElgAmountRate,
        Double buyLgAmount,
        Double buyLgAmountRate,
        Double buyMdAmount,
        Double buyMdAmountRate,
        Double buySmAmount,
        Double buySmAmountRate) {}
