package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `regime_ma200_breadth_daily`; source snapshot 2026-09-28. */
public record RegimeMa200BreadthDailyRow(
        Instant tradeDate,
        Integer aboveMa200Count,
        Integer eligibleCount,
        Integer targetUniverseCount,
        Integer insufficientHistoryCount,
        Double breadthRatio,
        Double coverageRatio,
        Integer universeSourceCount,
        Integer excludedNonAShareCount,
        Integer excludedStCount,
        Integer excludedSuspendedCount,
        String universeVersion,
        String universeFingerprint,
        Double hs300Close,
        Instant hs300SourceAsOf,
        String hs300QualityStatus,
        String hs300ReasonCode,
        String hs300ReasonMessage,
        String qualityStatus,
        String reasonCode,
        String reasonMessage,
        String methodVersion,
        String sourceLineage,
        String inputFingerprint,
        String runId,
        Instant computedAt) {}
