package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `regime_erp_source_status_daily`; source snapshot 2026-09-28. */
public record RegimeErpSourceStatusDailyRow(
        Instant evaluationDate,
        Instant evaluatedAt,
        String sourceId,
        String indexId,
        String valuationMetric,
        Boolean authorized,
        Boolean sourceAvailable,
        Instant sourceAsOf,
        Instant bondAsOf,
        String qualityStatus,
        String reasonCode,
        String reasonMessage,
        String methodVersion,
        String sourceLineage,
        String inputFingerprint,
        String runId) {}
