package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `regime_display_materialization_run`; source snapshot 2026-09-28. */
public record RegimeDisplayMaterializationRunRow(
        Instant startedAt,
        String runId,
        String metricId,
        String mode,
        Instant requestedStartDate,
        Instant requestedEndDate,
        Instant sourceAsOf,
        String runStatus,
        String qualityStatus,
        String reasonCode,
        String reasonMessage,
        Integer rowsEvaluated,
        Integer rowsWritten,
        String inputFingerprint,
        String methodVersion,
        Instant completedAt) {}
