package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `regime_stock_return_distribution_daily`; source snapshot 2026-09-28. */
public record RegimeStockReturnDistributionDailyRow(
        Instant asOf,
        String window,
        Instant windowStartAsOf,
        Integer bucketOrder,
        String bucketId,
        String label,
        Double lowerBound,
        Boolean lowerInclusive,
        Double upperBound,
        Boolean upperInclusive,
        Integer stockCount,
        Double stockPct,
        Integer validReturnCount,
        Integer targetUniverseCount,
        Integer missingStartCount,
        Integer missingEndCount,
        Integer universeSourceCount,
        Integer excludedNonAShareCount,
        Integer excludedStCount,
        Integer excludedSuspendedCount,
        String universeVersion,
        String universeFingerprint,
        String qualityStatus,
        String reasonCode,
        String reasonMessage,
        Double coverageRatio,
        String methodVersion,
        String sourceLineage,
        String inputFingerprint,
        String runId,
        Instant computedAt) {}
