package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `shibor_lpr`; source snapshot 2026-09-28. */
public record ShiborLprRow(
        Instant date,
        Double field1y,
        Double field5y) {}
