package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stk_factor`; source snapshot 2026-09-28. */
public record StkFactorRow(
        String tsCode,
        Instant tradeDate,
        Double close,
        Double open,
        Double high,
        Double low,
        Double preClose,
        Double change,
        Double pctChange,
        Double vol,
        Double amount,
        Double adjFactor,
        Double openHfq,
        Double openQfq,
        Double closeHfq,
        Double closeQfq,
        Double highHfq,
        Double highQfq,
        Double lowHfq,
        Double lowQfq,
        Double preCloseHfq,
        Double preCloseQfq,
        Double macdDif,
        Double macdDea,
        Double macd,
        Double kdjK,
        Double kdjD,
        Double kdjJ,
        Double rsi6,
        Double rsi12,
        Double rsi24,
        Double bollUpper,
        Double bollMid,
        Double bollLower,
        Double cci) {}
