package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stk_holdertrade`; source snapshot 2026-09-28. */
public record StkHoldertradeRow(
        String tsCode,
        Instant annDate,
        String holderName,
        String holderType,
        String inDe,
        Double changeVol,
        Double changeRatio,
        Double afterShare,
        Double afterRatio,
        Double avgPrice,
        Double totalShare,
        String beginDate,
        String closeDate) {}
