package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stk_high_shock`; source snapshot 2026-09-28. */
public record StkHighShockRow(
        String tsCode,
        Instant tradeDate,
        String name,
        String tradeMarket,
        String reason,
        String period) {}
