package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stock_minute_bars`; source snapshot 2026-09-28. */
public record StockMinuteBarsRow(
        String tsCode,
        Instant barTime,
        Integer sourceRowIndex,
        Double open,
        Double high,
        Double low,
        Double close,
        Double volume,
        Double amount) {}
