package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_production_state_daily`; source snapshot 2026-09-28. */
public record StrategyProductionStateDailyRow(
        String runId,
        String strategyId,
        String instanceId,
        String sourceStrategy,
        String sourceRunId,
        String backtestRunId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String portfolioState,
        String stateTriggerReason,
        String stateAction,
        Double activeAlphaCount,
        Double riskOffCount,
        Double unstableCount,
        Double selectedAvgComponentL2,
        Double selectedAvgBuyBreadth,
        Double selectedOverheatRatio,
        Double selectedCrowdingRatio,
        Double selectedHotCrowdedRatio,
        Double avgPairCorr,
        Double avgComponentOverlap,
        Double top10HighVolWeight,
        Double top10LimitTouchWeight,
        Double componentCrowdingScore,
        Double overheatScore,
        Double currentDrawdown,
        Double netReturn,
        Double grossReturn,
        Double endEquity,
        String factorStateDetails,
        Instant createdAt) {}
