package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `us_trycr`; source snapshot 2026-09-28. */
public record UsTrycrRow(
        Instant date,
        Double y5,
        Double y7,
        Double y10,
        Double y20,
        Double y30) {}
