package com.zoutrankil.data.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_etf_market_overview_daily`; source snapshot 2026-09-28. */
public record EtfMarketOverviewDailyView(
        Instant tradeDate,
        Long etfCount,
        Double totalShare,
        Double totalSizeYi) {}
