package com.zoutrankil.data.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_market_breadth_monthly`; source snapshot 2026-09-28. */
public record MarketBreadthMonthlyView(
        Instant month,
        Double avgUpCount,
        Double avgDownCount,
        Double avgFlatCount,
        Double avgUpDownRatio,
        Double avgLimitUpCount,
        Double avgLimitDownCount,
        Double monthTotalAmount,
        Double avgTurnoverRate,
        Double medianTurnoverRate,
        Double avgPctPositiveRatio,
        Double avgPctNegativeRatio,
        Double tradableStockCountMonthEnd) {}
