package com.zoutrankil.data.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_market_breadth_daily`; source snapshot 2026-09-28. */
public record MarketBreadthDailyView(
        Instant tradeDate,
        Long stockCount,
        Long upCount,
        Long downCount,
        Long flatCount,
        Double avgPctChange,
        Double totalAmountYi) {}
