package com.zoutrankil.data.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_regime_features_monitor_daily`; source snapshot 2026-09-28. */
public record RegimeFeaturesMonitorDailyView(
        Instant tradeDate,
        String month,
        Double hs300RetMtd,
        Double zz500RetMtd,
        Double allARetMtd,
        Double cs1000RetMtd,
        Double smallLargeRetMtd,
        Double growthValueRetMtd,
        Double avgUpDownRatio5d,
        Double avgLimitUpCount5d,
        Double avgLimitDownCount5d,
        Double avgTurnoverRate5d,
        Double avgPctPositiveRatio5d,
        Double avgPctNegativeRatio5d,
        Double northboundNetBuyMtd,
        Double marginBalanceChangeMtd,
        Double allAPeTtmPercentileLatest,
        Double allAPbPercentileLatest,
        Double erpLatest,
        String dataQualityFlag,
        Instant updatedAt) {}
