package com.zoutrankil.data.domain.materializedview;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `mv_market_breadth_daily_v1`; source snapshot 2026-09-28. */
public record MarketBreadthDailyV1MaterializedView(
        Instant tradeDate,
        Long stockCount,
        Long upCount,
        Long downCount,
        Long flatCount,
        Double avgPctChange,
        Double totalAmountYi) {}
