package com.zoutrankil.data.domain.materializedview;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `mv_retail_sentiment_daily_v1`; source snapshot 2026-09-28. */
public record RetailSentimentDailyV1MaterializedView(
        Instant tradeDate,
        Double avgRetailRatio,
        Double avgRetailEntropy,
        Double totalRetailAmountYi,
        Double totalRetailNetInflowYi,
        Double avgRelAggro,
        Long totalQ1,
        Long totalQ3,
        Double avgWashTradeRatio,
        Long totalSpoofCount,
        Long totalManipulationCount,
        Double avgMfiScore,
        Double totalMainNetYi) {}
