import com.fasterxml.jackson.databind.JsonNode;
import com.zoutrankil.questdbwithdata.domain.JobDefinitionJson;
import com.zoutrankil.questdbwithdata.domain.SyncRunState;
import com.zoutrankil.questdbwithdata.repository.SyncRunLedger;
import com.zoutrankil.questdbwithdata.service.StaticTargetIdentity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import java.math.BigDecimal;
import java.nio.file.*;
import java.security.MessageDigest;
import java.sql.SQLException;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;

/** Independent D026 raw-receipt-to-QuestDB oracle; it does not use MoneyflowDcSource/Mapper/WritePort. */
public final class MoneyflowDcIndependentReadback {
    private static final String JOB="data.moneyflow_dc";private static final int VERSION=2,ROW_CAP=10000,MAX_DAYS=5;
    private static final DateTimeFormatter BASIC=DateTimeFormatter.BASIC_ISO_DATE;
    private static final List<String> FIELDS=List.of("ts_code","trade_date","name","pct_change","close","net_amount","net_amount_rate","buy_elg_amount","buy_elg_amount_rate","buy_lg_amount","buy_lg_amount_rate","buy_md_amount","buy_md_amount_rate","buy_sm_amount","buy_sm_amount_rate");
    private static final List<String> NUMERIC=FIELDS.stream().filter(f->!Set.of("ts_code","trade_date","name").contains(f)).toList();
    private record Key(LocalDate date,String code){}
    private record Expected(Key key,Map<String,Object> values){}
    private record Actual(Key key,long micros,Map<String,Object> values){}
    private MoneyflowDcIndependentReadback(){}

    public static Map<String,Object> verify(JdbcTemplate jdbc,Path ledger,String table,String runId)throws Exception{
        Objects.requireNonNull(jdbc);Objects.requireNonNull(ledger);if(table==null||!table.matches("java_d026_moneyflow_dc_[A-Za-z0-9_]{1,80}")||runId==null||!runId.matches("[A-Za-z0-9_.-]{1,128}")||runId.contains(".."))throw new IllegalArgumentException("Explicit isolated D026 table and bounded run ID required");
        var json=JobDefinitionJson.mapper();var history=SyncRunLedger.openReadOnly(ledger.toAbsolutePath().normalize());var run=history.getRun(runId);var state=history.get(runId);
        if(!JOB.equals(run.jobId())||run.jobVersion()!=VERSION||!Set.of(SyncRunState.VERIFIED,SyncRunState.VERIFIED_EMPTY).contains(state.state()))throw new IllegalStateException("Terminal verified D026 run required");
        JsonNode frozen=json.readTree(run.frozenJson()),params=frozen.path("parameters");if(!JOB.equals(frozen.path("definition").path("jobId").asText())||frozen.path("definition").path("version").asInt(-1)!=VERSION)throw new IllegalStateException("Frozen D026 definition mismatch");
        String target=required(params,"targetId");if(!target.equals(run.targetId())||!target.matches("static-v2-[0-9a-f]{64}"))throw new IllegalStateException("D026 frozen physical target identity mismatch");var tables=jdbc.queryForList("SELECT id,directoryName FROM tables() WHERE table_name=?",table);if(tables.size()!=1||!(tables.getFirst().get("id") instanceof Number id)||!(tables.getFirst().get("directoryName") instanceof String directory)||!target.equals(StaticTargetIdentity.identify(jdbc,table,id.longValue(),directory)))throw new IllegalStateException("D026 physical target generation changed");
        LocalDate from=LocalDate.parse(required(frozen,"from")),to=LocalDate.parse(required(frozen,"to")),logicalDate=LocalDate.parse(required(frozen,"logicalDate"));long span=ChronoUnit.DAYS.between(from,to)+1;if(from.isBefore(LocalDate.of(2023,9,11))||from.isAfter(to)||span<1||span>MAX_DAYS||to.isAfter(logicalDate))throw new IllegalStateException("Frozen D026 date window exceeds source start/five-day/logical date bound");
        List<LocalDate> dates=decode(required(params,"trade_dates"),from,to);Path evidenceRoot=ledger.toAbsolutePath().normalize().getParent().resolve("sync-evidence").resolve(runId).toRealPath();
        var slices=history.entries(runId,null,1000).stream().filter(e->e.kind()==SyncRunLedger.Kind.SLICE).toList();if(slices.size()!=dates.size())throw new IllegalStateException("D026 slice count differs from frozen open dates");var byDate=new HashMap<LocalDate,SyncRunLedger.Entry>();
        for(var slice:slices){if(!Set.of(SyncRunState.VERIFIED,SyncRunState.VERIFIED_EMPTY).contains(slice.state()))throw new IllegalStateException("D026 run contains unverified source slice");var fetched=history.events(slice.id(),-1,100).stream().filter(e->e.state()==SyncRunState.FETCHED).toList();if(fetched.size()!=1)throw new IllegalStateException("Each D026 slice requires exactly one immutable FETCHED event");JsonNode event=json.readTree(fetched.getFirst().payloadJson());String cursor=required(event,"cursor");if(!cursor.matches("[0-9]{8}"))throw new IllegalStateException("D026 fetched cursor must be BASIC trade date");LocalDate date=LocalDate.parse(cursor,BASIC);if(!dates.contains(date)||byDate.putIfAbsent(date,slice)!=null)throw new IllegalStateException("D026 duplicate/out-of-range source slice");}
        var expected=new TreeMap<Key,Expected>(Comparator.comparing(Key::date).thenComparing(Key::code));var receiptProofs=new ArrayList<Map<String,Object>>();var fingerprints=new ArrayList<String>();long sourceRows=0,evidenceBytes=0,sourceDuplicates=0;
        for(LocalDate date:dates){var slice=byDate.get(date);JsonNode fetched=json.readTree(history.events(slice.id(),-1,100).stream().filter(e->e.state()==SyncRunState.FETCHED).findFirst().orElseThrow().payloadJson());int count=fetched.path("returnedRows").asInt(-1);String fingerprint=required(fetched,"sourceFingerprint");if(count<0||count>ROW_CAP||!fingerprint.matches("[0-9a-f]{64}")||!date.format(BASIC).equals(required(fetched,"cursor")))throw new IllegalStateException("D026 FETCHED event violates date/cap/fingerprint");
            Path receipt=safeEvidence(evidenceRoot.resolve("source").toRealPath(),required(fetched,"responseEvidence"));byte[] bytes=Files.readAllBytes(receipt);evidenceBytes=Math.addExact(evidenceBytes,bytes.length);if(evidenceBytes>MAX_DAYS*16L*1024*1024||!sha(bytes).equals(fingerprint))throw new IllegalStateException("D026 raw receipt SHA/aggregate size invalid");JsonNode proof=json.readTree(bytes);validateReceipt(proof,date,count);verifyPageProofs(proof);
            if((count==0)!=(slice.state()==SyncRunState.VERIFIED_EMPTY))throw new IllegalStateException("D026 slice state differs from raw response");for(JsonNode raw:proof.path("rawRows")){Expected row=normalize(raw,date);if(expected.putIfAbsent(row.key(),row)!=null)sourceDuplicates++;}
            sourceRows=Math.addExact(sourceRows,count);fingerprints.add(fingerprint);receiptProofs.add(Map.of("tradeDate",date.toString(),"rows",count,"sourceFingerprint",fingerprint,"responseEvidence",receipt.toString()));}
        Path completion=safeEvidence(evidenceRoot,evidenceRoot.resolve("complete-window.json").toString());JsonNode complete=json.readTree(completion.toFile());String combined=combine(fingerprints);
        if(!complete.path("complete").asBoolean(false)||!complete.path("sourceComplete").asBoolean(false)||!complete.path("dedup").asBoolean(false)||!target.equals(required(complete,"targetId"))||!from.toString().equals(required(complete,"fromInclusive"))||!to.toString().equals(required(complete,"toInclusive"))||!json.valueToTree(dates).equals(complete.path("tradeDates"))||complete.path("completedDateSlices").asInt(-1)!=dates.size()||complete.path("sourceRows").asLong(-1)!=sourceRows||complete.path("returnedRows").asLong(-1)!=sourceRows||complete.path("writeCandidateRows").asLong(-1)!=sourceRows||(sourceRows==0?complete.path("submittedRows").asLong(-1)!=0:!complete.path("submittedRows").isNull())||!combined.equals(required(complete,"sourceFingerprint"))||!json.valueToTree(receiptProofs).equals(complete.path("sourceReceipts")))throw new IllegalStateException("D026 completion receipt differs from frozen daily receipts");
        String selected=String.join(",",FIELDS.stream().map(f->"\""+f+"\"").toList());String sql="SELECT "+selected+",cast(trade_date AS long) AS trade_date_micros FROM \""+table+"\" WHERE trade_date>=cast(? AS TIMESTAMP) AND trade_date<cast(? AS TIMESTAMP) ORDER BY trade_date,ts_code LIMIT "+(MAX_DAYS*ROW_CAP+1);
        List<Actual> actual=jdbc.query(sql,actualMapper(),micros(from),micros(to.plusDays(1)));if(actual.size()>MAX_DAYS*ROW_CAP)throw new IllegalStateException("D026 physical readback exceeds five-day row bound");var actualByKey=new HashMap<Key,Actual>();long duplicates=0,extras=0,missing=0,mismatches=0,matched=0;var samples=new ArrayList<String>();
        for(var row:actual){if(actualByKey.putIfAbsent(row.key(),row)!=null){duplicates++;sample(samples,"duplicate-target:"+row.key());}if(!expected.containsKey(row.key())){extras++;sample(samples,"unexpected-target:"+row.key());}}
        for(var e:expected.entrySet()){Actual row=actualByKey.get(e.getKey());if(row==null){missing++;sample(samples,"missing:"+e.getKey());continue;}boolean mismatch=row.micros()!=micros(e.getKey().date());for(String f:FIELDS){if(f.equals("ts_code")||f.equals("trade_date"))continue;if(!same(e.getValue().values().get(f),row.values().get(f))){mismatch=true;sample(samples,"value:"+e.getKey()+":"+f);}}if(mismatch)mismatches++;else matched++;}
        boolean ok=sourceDuplicates==0&&duplicates==0&&extras==0&&missing==0&&mismatches==0&&actual.size()==expected.size();return Map.ofEntries(Map.entry("status",ok?"MATCHED":"MISMATCH"),Map.entry("dataset","moneyflow_dc"),Map.entry("table",table),Map.entry("runId",runId),Map.entry("targetId",target),Map.entry("fromInclusive",from.toString()),Map.entry("toInclusive",to.toString()),Map.entry("tradeDates",dates.stream().map(LocalDate::toString).toList()),Map.entry("sourceRows",sourceRows),Map.entry("actualRows",actual.size()),Map.entry("matchedRows",matched),Map.entry("mismatchedRows",mismatches),Map.entry("sourceDuplicateKeys",sourceDuplicates),Map.entry("duplicateKeys",duplicates),Map.entry("missingKeys",missing),Map.entry("extraKeys",extras),Map.entry("evidenceBytes",evidenceBytes),Map.entry("receiptFingerprints",fingerprints),Map.entry("mismatchSamples",samples));
    }
    private static void validateReceipt(JsonNode r,LocalDate date,int rows){if(!"tushare".equals(r.path("sourceKind").asText())||!"moneyflow_dc".equals(r.path("endpoint").asText())||!r.path("sourceComplete").asBoolean(false)||!date.toString().equals(r.path("tradeDate").asText())||r.path("apiMaximumRows").asInt(-1)!=6000||r.path("returnedRows").asInt(-1)!=rows||rows>ROW_CAP||!r.path("rawRows").isArray()||r.path("rawRows").size()!=rows||!JobDefinitionJson.mapper().valueToTree(FIELDS).equals(r.path("fields"))||!date.format(BASIC).equals(r.path("parameters").path("trade_date").asText()))throw new IllegalStateException("D026 receipt differs from frozen endpoint/date/fields/cap");}
    private static void verifyPageProofs(JsonNode proof){
        if(proof.path("receiptVersion").asInt()!=2||proof.path("dailyRowBound").asInt()!=ROW_CAP||proof.path("pageSize").asInt()!=2000)
            throw new IllegalStateException("D026 receipt paging contract mismatch");
        var pages=proof.path("pageProofs");if(!pages.isArray()||pages.isEmpty()||pages.size()>6)throw new IllegalStateException("D026 missing bounded page proofs");
        var observed=new HashSet<String>();int offset=0;
        for(int i=0;i<pages.size();i++){var page=pages.get(i);int count=page.path("returnedRows").asInt(-1);var keys=page.path("keys");
            if(page.path("offset").asInt(-1)!=offset||page.path("limit").asInt(-1)!=2000||count<0||count>2000
                    ||!keys.isArray()||keys.size()!=count||(i==pages.size()-1?count>=2000:count!=2000))
                throw new IllegalStateException("D026 offset/limit/terminal-page proof invalid");
            for(var key:keys)if(!key.isTextual()||!observed.add(key.asText()))throw new IllegalStateException("D026 page key repeated");offset=Math.addExact(offset,count);
        }
        var expected=new HashSet<String>();for(var row:proof.path("rawRows"))if(!expected.add(row.path("ts_code").asText()+"/"+row.path("trade_date").asText()))throw new IllegalStateException("D026 raw key repeated");
        if(offset>ROW_CAP||offset!=proof.path("returnedRows").asInt(-1)||!observed.equals(expected))throw new IllegalStateException("D026 page inventory differs from complete raw source");
    }
    private static Expected normalize(JsonNode row,LocalDate date){var fields=new TreeSet<String>();row.fieldNames().forEachRemaining(fields::add);if(!fields.equals(new TreeSet<>(FIELDS)))throw new IllegalStateException("D026 raw row fields differ from 15-column contract");String code=text(row,"ts_code");if(!code.matches("[0-9]{6}\\.(SZ|SH|BJ)")||!date.format(BASIC).equals(text(row,"trade_date")))throw new IllegalStateException("D026 source code/date outside frozen slice");var values=new LinkedHashMap<String,Object>();values.put("ts_code",code);values.put("trade_date",date);JsonNode name=row.get("name");if(name!=null&&!name.isNull()&&!name.isTextual())throw new IllegalStateException("D026 name is not text/null");values.put("name",name==null||name.isNull()?null:name.textValue());for(String f:NUMERIC)values.put(f,amount(row.get(f),f));return new Expected(new Key(date,code),values);}
    private static RowMapper<Actual> actualMapper(){return (rs,n)->{Object raw=rs.getObject("trade_date_micros");if(!(raw instanceof Number t))throw new SQLException("D026 trade_date timestamp missing");LocalDate date=fromMicros(t.longValue());var values=new LinkedHashMap<String,Object>();String code=rs.getString("ts_code");values.put("ts_code",code);values.put("trade_date",date);values.put("name",rs.getString("name"));for(String f:NUMERIC){Object v=rs.getObject(f);values.put(f,v==null?null:((Number)v).doubleValue());}return new Actual(new Key(date,code),t.longValue(),values);};}
    private static String text(JsonNode row,String f){JsonNode v=row.get(f);if(v==null||v.isNull()||!v.isTextual()||v.asText().isBlank())throw new IllegalStateException("D026 required text missing: "+f);return v.textValue();}
    private static Double amount(JsonNode v,String f){if(v==null||v.isNull()||v.isTextual()&&v.asText().isBlank())return null;try{double n=new BigDecimal(v.asText()).doubleValue();if(!Double.isFinite(n))throw new NumberFormatException();return n;}catch(Exception e){throw new IllegalStateException("D026 finite DOUBLE invalid: "+f,e);}}
    private static boolean same(Object a,Object b){if(a==null||b==null)return a==b;if(a instanceof Number x&&b instanceof Number y)return Double.compare(x.doubleValue(),y.doubleValue())==0;return a.equals(b);}
    private static List<LocalDate> decode(String raw,LocalDate from,LocalDate to){var out=Arrays.stream(raw.split(",",-1)).map(s->{if(!s.matches("[0-9]{8}"))throw new IllegalStateException("D026 trade date requires YYYYMMDD");return LocalDate.parse(s,BASIC);}).toList();if(out.isEmpty()||out.size()>MAX_DAYS||out.stream().distinct().count()!=out.size()||!out.equals(out.stream().sorted().toList())||out.stream().anyMatch(d->d.isBefore(from)||d.isAfter(to)))throw new IllegalStateException("D026 frozen dates duplicate/unordered/outside range");return out;}
    private static Path safeEvidence(Path root,String ref)throws Exception{Path p=Path.of(ref).toAbsolutePath().normalize();if(!p.startsWith(root)||!Files.isRegularFile(p)||!p.toRealPath().startsWith(root)||Files.size(p)>MoneyflowDcEvidenceCap.MAX_BYTES)throw new IllegalStateException("D026 evidence absent/outside/oversized");return p;}
    private static String required(JsonNode n,String f){JsonNode v=n.path(f);if(!v.isTextual()||v.asText().isBlank())throw new IllegalStateException("D026 evidence missing "+f);return v.asText();}
    private static long micros(LocalDate d){return d.atStartOfDay(ZoneOffset.UTC).toEpochSecond()*1_000_000L;}private static LocalDate fromMicros(long v){long sec=Math.floorDiv(v,1_000_000),r=Math.floorMod(v,1_000_000);var instant=Instant.ofEpochSecond(sec,r*1000);if(!instant.atOffset(ZoneOffset.UTC).toLocalTime().equals(LocalTime.MIDNIGHT))throw new IllegalStateException("D026 trade timestamp is not a UTC-midnight date carrier");return instant.atOffset(ZoneOffset.UTC).toLocalDate();}
    private static String sha(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}private static String combine(List<String> parts)throws Exception{var d=MessageDigest.getInstance("SHA-256");for(String p:parts){d.update(p.getBytes(java.nio.charset.StandardCharsets.UTF_8));d.update((byte)0);}return HexFormat.of().formatHex(d.digest());}
    private static void sample(List<String> list,String value){if(list.size()<20)list.add(value);}
    /** Kept local to this offline evidence tool so it remains independent of the production source class. */
    private static final class MoneyflowDcEvidenceCap { private static final long MAX_BYTES=16L*1024*1024; }
}
