package com.zoutrankil.data.domain.view;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `v_macro_liquidity_credit_monthly`; source snapshot 2026-09-28. */
public record MacroLiquidityCreditMonthlyView(
        Instant month,
        Double rmbIndexMonthEnd,
        Double rmbIndexRet1m,
        Double shiborOnMonthAvg,
        Double shibor1wMonthAvg,
        Double shibor3mMonthAvg,
        Double shibor1yMonthAvg,
        Double lpr1yMonthEnd,
        Double lpr5yMonthEnd,
        Double shiborSlope1w3mMonthAvg,
        Double shiborSlope3m1yMonthAvg,
        Double gov3yMonthEnd,
        Double gov5yMonthEnd,
        Double gov7yMonthEnd,
        Double gov10yMonthEnd,
        Double aaaMtn3yMonthEnd,
        Double aaaMtn5yMonthEnd,
        Double aaaMtn7yMonthEnd,
        Double aaaMtn10yMonthEnd,
        Double aaaBank3yMonthEnd,
        Double aaaBank5yMonthEnd,
        Double aaaBank7yMonthEnd,
        Double aaaBank10yMonthEnd,
        Double creditSpreadAaaGov3y,
        Double creditSpreadAaaGov5y,
        Double creditSpreadAaaGov7y,
        Double creditSpreadAaaGov10y,
        Double spreadAaaBankGov3y,
        Double spreadAaaBankGov5y,
        Double spreadAaaBankGov7y,
        Double spreadAaaBankGov10y,
        Double spreadBankMtn3y,
        Double spreadBankMtn5y,
        Double spreadBankMtn7y,
        Double spreadBankMtn10y,
        Double termSpread) {}
