package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cn_bond_yield_curve`; source snapshot 2026-09-28. */
public record CnBondYieldCurveRow(
        Instant tradeDate,
        String curveName,
        String curveCode,
        String tenor,
        Double yieldValue,
        String source) {}
