package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `cyq_perf`; source snapshot 2026-09-28. */
public record CyqPerfRow(
        String tsCode,
        Instant tradeDate,
        Double winnerRate,
        Double weightAvg,
        Double cost5pct,
        Double cost15pct,
        Double cost50pct,
        Double cost85pct,
        Double cost95pct,
        Double hisLow,
        Double hisHigh) {}
