package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `daily_basic`; source snapshot 2026-09-28. */
public record DailyBasicRow(
        String tsCode,
        Instant tradeDate,
        Double close,
        Double turnoverRate,
        Double turnoverRateF,
        Double volumeRatio,
        Double pe,
        Double peTtm,
        Double pb,
        Double ps,
        Double psTtm,
        Double dvRatio,
        Double dvTtm,
        Double totalShare,
        Double floatShare,
        Double freeShare,
        Double totalMv,
        Double circMv) {}
