package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `dc_index`; source snapshot 2026-09-28. */
public record DcIndexRow(
        String tsCode,
        Instant tradeDate,
        String name,
        String leading,
        String leadingCode,
        Double pctChange,
        Double leadingPct,
        Double totalMv,
        Double turnoverRate,
        Integer upNum,
        Integer downNum) {}
