package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `disclosure_date`; source snapshot 2026-09-28. */
public record DisclosureDateRow(
        String tsCode,
        Instant annDate,
        String endDate,
        String preDate,
        String actualDate,
        String modifyDate,
        Instant updateTime) {}
