package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `equity_style_monthly`; source snapshot 2026-09-28. */
public record EquityStyleMonthlyRow(
        Instant month,
        Double hs300Ret1m,
        Double zz500Ret1m,
        Double allARet1m,
        Double cs1000Ret1m,
        Double smallLargeRet1m,
        Double midLargeRet1m,
        Double growthRet1m,
        Double valueRet1m,
        Double growthValueRet1m,
        Double energyRet1m,
        Double materialsRet1m,
        Double industrialsRet1m,
        Double consumerDiscretionaryRet1m,
        Double consumerStaplesRet1m,
        Double healthcareRet1m,
        Double financialsRet1m,
        Double itRet1m,
        Double telecomRet1m,
        Double utilitiesRet1m,
        Double energyVsAllA1m,
        Double materialsVsAllA1m,
        Double industrialsVsAllA1m,
        Double consumerDiscretionaryVsAllA1m,
        Double consumerStaplesVsAllA1m,
        Double healthcareVsAllA1m,
        Double financialsVsAllA1m,
        Double itVsAllA1m,
        Double telecomVsAllA1m,
        Double utilitiesVsAllA1m) {}
