package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `etf_adj`; source snapshot 2026-09-28. */
public record EtfAdjRow(
        String tsCode,
        Double adjFactor,
        Instant timestamp) {}
