package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_ic_daily`; source snapshot 2026-09-28. */
public record FactorIcDailyRow(
        Instant tradeDate,
        String factorId,
        String universeId,
        Instant signalDate,
        Instant maturityDate,
        Instant availableAt,
        String definitionVersion,
        String factorFamily,
        String sourceGroup,
        String directionPrior,
        String horizon,
        Double rawRankIc,
        Double rankIc,
        Double directionAdjustedRankIc,
        Double topMinusBottom,
        Double topBucketMean,
        Double topBucketWorst,
        Double positiveTopRate,
        Double decileLongShort,
        Double decileMonotonicity,
        Double factorAutocorrelation,
        Double decile1MeanReturn,
        Double decile2MeanReturn,
        Double decile3MeanReturn,
        Double decile4MeanReturn,
        Double decile5MeanReturn,
        Double decile6MeanReturn,
        Double decile7MeanReturn,
        Double decile8MeanReturn,
        Double decile9MeanReturn,
        Double decile10MeanReturn,
        Double coverage,
        Double tradableRate,
        Integer sampleCount,
        String runId) {}
