package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_registry`; source snapshot 2026-09-28. */
public record FactorRegistryRow(
        Instant updatedAt,
        String runId,
        String factorId,
        String definitionVersion,
        String assetType,
        String sourceGroup,
        String sourceTable,
        String sourceColumn,
        String formula,
        String factorFamily,
        String frequency,
        String role,
        String variantId,
        Boolean isCanonical,
        String validationProfile,
        String lifecycleStatus,
        String lineageParentId,
        String lineageParentVersion,
        String changeReason,
        String directionPrior,
        String transform,
        String pitPolicy,
        Boolean enabled,
        Boolean promoteToDb,
        Boolean promoted,
        Double evidenceScore,
        String category,
        String horizon,
        Integer lookbackPeriods,
        String parameters,
        String neutralizePolicy,
        String normalizePolicy,
        String decayPolicy,
        String owner,
        String aliases) {}
