package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_catalog`; source snapshot 2026-09-28. */
public record FactorCatalogRow(
        Instant updatedAt,
        String factorId,
        String definitionVersion,
        String nameZh,
        String nameEn,
        String factorFamily,
        String role,
        String lifecycleStatus,
        String direction,
        String frequency,
        String formula,
        String sourceRef,
        String definitionDigest,
        Boolean enabled) {}
