package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_materialization_run`; source snapshot 2026-09-28. */
public record FactorMaterializationRunRow(
        Instant periodEnd,
        Instant periodStart,
        String factorId,
        String definitionVersion,
        String frequency,
        String entityScope,
        String universeId,
        String inputFingerprint,
        String action,
        String status,
        Integer expectedEntityCount,
        Integer actualEntityCount,
        Double coverageRatio,
        String reason,
        String runId,
        Instant startedAt,
        Instant completedAt) {}
