package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_dependency`; source snapshot 2026-09-28. */
public record FactorDependencyRow(
        Instant registeredAt,
        String factorId,
        String definitionVersion,
        String dependencyId,
        String dependencyKind,
        String relation,
        Boolean required,
        String runId) {}
