package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `factor_platform_run`; source snapshot 2026-09-28. */
public record FactorPlatformRunRow(
        Instant runAt,
        String runId,
        String consumer,
        Instant startDate,
        Instant endDate,
        String definitionVersion,
        Integer factorCount,
        Integer promotedCount,
        String notes,
        String inputFingerprint) {}
