package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `ft_limit`; source snapshot 2026-09-28. */
public record FtLimitRow(
        Instant tradeDate,
        String tsCode,
        String name,
        Double upLimit,
        Double downLimit,
        Double mRatio,
        String cont,
        String exchange,
        Instant updateTime) {}
