package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_index_daily_snapshot`; source snapshot 2026-09-28. */
public record FutIndexDailySnapshotRow(
        Instant tradeDate,
        String futCode,
        String mainTsCode,
        String mappingTsCode,
        String spotIndexCode,
        Double futClose,
        Double futSettle,
        Double spotClose,
        Double futRet1d,
        Double spotRet1d,
        Double basisPoints,
        Double basisPct,
        Double annualizedBasisPct,
        Integer daysToExpiry,
        Double vol,
        Double oi,
        Double oiChg,
        Double top20Long,
        Double top20Short,
        Double top20Net,
        Double top20NetChg,
        Double longMarginRate,
        Double shortMarginRate,
        Double upLimit,
        Double downLimit,
        String dataQualityFlag,
        Instant updatedAt) {}
