package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_index_conclusion_daily`; source snapshot 2026-09-28. */
public record FutIndexConclusionDailyRow(
        Instant tradeDate,
        String futCode,
        String mainTsCode,
        String mappingTsCode,
        String spotIndexCode,
        String direction,
        String strength,
        String styleTag,
        Double confidence,
        Double rawScore,
        String summary,
        String riskNote,
        String drivers,
        String dataQualityFlag,
        Instant updatedAt) {}
