package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `fut_mapping`; source snapshot 2026-09-28. */
public record FutMappingRow(
        String tsCode,
        Instant tradeDate,
        String mappingTsCode,
        Instant updateTime) {}
