package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `hibor`; source snapshot 2026-09-28. */
public record HiborRow(
        Instant timestamp,
        Double on,
        Double field1w,
        Double field2w,
        Double field1m,
        Double field2m,
        Double field3m,
        Double field6m,
        Double field12m) {}
