package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `index_weight`; source snapshot 2026-09-28. */
public record IndexWeightRow(
        String indexCode,
        String conCode,
        Instant tradeDate,
        String indexName,
        String indexNameEn,
        String conName,
        String conNameEn,
        String exchange,
        String exchangeEn,
        Double weight,
        Instant updateTime) {}
