package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `industry_intrinsic_valuation_state`; source snapshot 2026-09-28. */
public record IndustryIntrinsicValuationStateRow(
        Instant valuationDate,
        String industryL2,
        String routeId,
        Double industryIntrinsicUpside,
        Double industryHistoricalPercentile,
        Double industryPeerPercentile,
        Double industryValuationDispersion,
        Double industryCoverage,
        Double industryConfidence,
        Integer companyCount,
        Integer coveredCompanyCount,
        Double industryPeTtm,
        Double industryPb,
        Double peHistoricalPercentile,
        Double pbHistoricalPercentile,
        Double pePeerPercentile,
        Double pbPeerPercentile,
        String valuationState,
        String routeVersion,
        String assumptionVersion,
        String runId) {}
