package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `l2_dataset_manifest`; source snapshot 2026-09-28. */
public record L2DatasetManifestRow(
        String tradeDate,
        String symbol,
        String market,
        String board,
        String sourceRoot,
        String outputRoot,
        String featureVersion,
        Boolean dailyFeatureOk,
        Boolean t0Ok,
        String rawRowCounts,
        String outputPaths,
        String costConfig,
        String horizonsMin,
        String errors,
        Long batchId,
        Instant tradeDateTs) {}
