package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `margin_trading`; source snapshot 2026-09-28. */
public record MarginTradingRow(
        String tsCode,
        Instant tradeDate,
        Double rzye,
        Double rzmre,
        Double rzche,
        Double rqyl,
        Double rqmcl,
        Double rqchl,
        Double rqye,
        Double rzrqye) {}
