package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `market_barometer_cache_coverage`; source snapshot 2026-09-28. */
public record MarketBarometerCacheCoverageRow(
        Instant tradeDate,
        String datasetId,
        String sourceVersion,
        Long rowCount,
        String contentDigest) {}
