package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `moneyflow_hsgt`; source snapshot 2026-09-28. */
public record MoneyflowHsgtRow(
        Instant tradeDate,
        Double ggtSs,
        Double ggtSz,
        Double hgt,
        Double sgt,
        Double northMoney,
        Double southMoney) {}
