package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `order_records`; source snapshot 2026-09-28. */
public record OrderRecordsRow(
        String recordId,
        String tsCode,
        String symbol,
        String stockName,
        String side,
        Integer quantity,
        Integer filledQuantity,
        Double price,
        Double amount,
        String status,
        String accountName,
        String strategyName,
        String brokerOrderId,
        String signalId,
        String orderType,
        String executionMode,
        String source,
        Instant submittedAt,
        Instant executedAt,
        Instant createdAt,
        String note,
        String extra,
        String orderId) {}
