package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_1m_bars`; source snapshot 2026-09-28. */
public record Qmt1mBarsRow(
        String tsCode,
        Instant barTime,
        String period,
        Double open,
        Double high,
        Double low,
        Double close,
        Double volume,
        Double amount,
        String source,
        Instant updatedAt) {}
