package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_assets`; source snapshot 2026-09-28. */
public record QmtAssetsRow(
        Double cash,
        Double frozenCash,
        Double marketValue,
        Double totalAsset,
        String accountId,
        Instant queryTime,
        String brokerName) {}
