package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_positions`; source snapshot 2026-09-28. */
public record QmtPositionsRow(
        String tsCode,
        Integer volume,
        Integer availableVolume,
        Double avgPrice,
        Double marketValue,
        Double profit,
        Double profitRatio,
        Double currentPrice,
        String stockName,
        String accountId,
        Instant queryTime,
        String brokerName) {}
