package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `qmt_tick_data`; source snapshot 2026-09-28. */
public record QmtTickDataRow(
        Instant tickTime,
        String timetag,
        Double lastPrice,
        Double open,
        Double high,
        Double low,
        Double lastClose,
        Double amount,
        Integer volume,
        Integer pvolume,
        Integer stockStatus,
        Integer openInt,
        Double settlementPrice,
        Double lastSettlementPrice,
        String askPrice,
        String bidPrice,
        String askVol,
        String bidVol,
        String tsCode,
        Long time) {}
