package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `share_float`; source snapshot 2026-09-28. */
public record ShareFloatRow(
        String tsCode,
        String annDate,
        Instant floatDate,
        Double floatShare,
        Double floatRatio,
        String holderName,
        String shareType) {}
