package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `stk_alert`; source snapshot 2026-09-28. */
public record StkAlertRow(
        String tsCode,
        String name,
        Instant startDate,
        String endDate,
        String type) {}
