package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_backtest_trades`; source snapshot 2026-09-28. */
public record StrategyBacktestTradesRow(
        String runId,
        String strategyId,
        String instanceId,
        Instant signalDate,
        Instant executionDate,
        Instant valuationDate,
        String symbol,
        String assetType,
        String side,
        Double weightDelta,
        Double tradeValue,
        Double commission,
        Double stampTax,
        Double cost,
        String name) {}
