package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `strategy_templates`; source snapshot 2026-09-28. */
public record StrategyTemplatesRow(
        String strategyCodeId,
        String name,
        String category,
        String tags,
        String description,
        String version,
        String author,
        String metadata,
        String inputSchema,
        String defaultParams,
        Boolean active,
        Instant createdAt,
        Instant updatedAt) {}
