package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `ths_member`; source snapshot 2026-09-28. */
public record ThsMemberRow(
        String tsCode,
        String conCode,
        String conName,
        Double weight,
        String inDate,
        String outDate,
        String isNew,
        Instant updateTime) {}
