package com.zoutrankil.data.domain.table;

import java.time.Instant;

// Generated by tools/generate_domain_models.py. Do not edit by hand.
/** Schema projection for QuestDB object `us_tycr`; source snapshot 2026-09-28. */
public record UsTycrRow(
        Instant date,
        Double m1,
        Double m2,
        Double m3,
        Double m4,
        Double m6,
        Double y1,
        Double y2,
        Double y3,
        Double y5,
        Double y7,
        Double y10,
        Double y20,
        Double y30) {}
