#!/usr/bin/env python3
"""Generate Java schema row/read-model records from an exported QuestDB domain catalog."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


MARKER = "// Generated by tools/generate_domain_models.py. Do not edit by hand."
PACKAGE_ROOT = Path("src/main/java/com/zoutrankil/questdbwithdata/domain")
PACKAGE_BY_TYPE = {
    "TABLE": ("table", "Row"),
    "VIEW": ("view", "View"),
    "MATERIALIZED_VIEW": ("materializedview", "MaterializedView"),
}
JAVA_KEYWORDS = set(
    "abstract assert boolean break byte case catch char class const continue default do "
    "double else enum extends final finally float for goto if implements import instanceof "
    "int interface long native new package private protected public return short static "
    "strictfp super switch synchronized this throw throws transient try void volatile while "
    "record sealed permits var yield true false null _".split()
)


def pascal_case(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.split("_") if part)


def camel_case(value: str) -> str:
    parts = [part for part in value.split("_") if part]
    result = (parts[0][:1].lower() + parts[0][1:]) + "".join(
        part[:1].upper() + part[1:] for part in parts[1:]
    )
    return f"field{result}" if result[:1].isdigit() else result


def java_source(package: str, class_name: str, obj: dict) -> str:
    components = []
    seen = set()
    for column in obj["columns"]:
        field_name = camel_case(column["name"])
        if not re.fullmatch(r"[A-Za-z_$][\w$]*", field_name) or field_name in JAVA_KEYWORDS:
            raise ValueError(f"Invalid Java field {obj['name']}.{column['name']} -> {field_name}")
        if field_name in seen:
            raise ValueError(f"Field name collision in {obj['name']}: {field_name}")
        seen.add(field_name)
        java_type = column["javaType"]
        if java_type == "MANUAL_MAPPING":
            raise ValueError(f"No Java type mapping for {obj['name']}.{column['name']}")
        components.append(f"        {java_type} {field_name}")
    if not components:
        raise ValueError(f"No output columns found for {obj['name']}")
    fields = ",\n".join(components)
    return (
        f"package {package};\n\n"
        "import java.time.Instant;\n\n"
        f"{MARKER}\n"
        f"/** Schema projection for QuestDB object `{obj['name']}`; source snapshot {obj['snapshotDate']}. */\n"
        f"public record {class_name}(\n{fields}) {{}}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--catalog",
        type=Path,
        default=Path("schema-export/questdb-qdb-2026-09-28/domain-catalog.json"),
    )
    args = parser.parse_args()
    catalog = json.loads(args.catalog.read_text())
    expected_paths: set[Path] = set()
    generated_count = 0

    for obj in catalog["objects"]:
        kind = obj["objectType"]
        if kind not in PACKAGE_BY_TYPE or not obj.get("domainClass"):
            continue
        folder, suffix = PACKAGE_BY_TYPE[kind]
        obj["snapshotDate"] = catalog["snapshotDate"]
        package = f"com.zoutrankil.data.domain.{folder}"
        class_name = obj["domainClass"]
        path = PACKAGE_ROOT / folder / f"{class_name}.java"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(java_source(package, class_name, obj))
        expected_paths.add(path.resolve())
        generated_count += 1

    for folder in PACKAGE_BY_TYPE.values():
        package_dir = PACKAGE_ROOT / folder[0]
        if not package_dir.exists():
            continue
        for path in package_dir.glob("*.java"):
            if path.resolve() not in expected_paths and path.read_text().startswith("package "):
                content = path.read_text()
                if MARKER in content:
                    path.unlink()

    print(f"Generated {generated_count} schema projection records from {args.catalog}")


if __name__ == "__main__":
    main()
