#!/usr/bin/env python3
"""Generate Java schema projections after validating the complete output plan."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import date
import json
import re
from pathlib import Path


MARKER = "// Generated by tools/generate_domain_models.py. Do not edit by hand."
PACKAGE_ROOT = Path("data-app/src/main/java/com/zoutrankil/data/domain")
PACKAGE_BY_TYPE = {
    "TABLE": ("table", "Row"),
    "VIEW": ("view", "View"),
    "MATERIALIZED_VIEW": ("materializedview", "MaterializedView"),
}
JAVA_KEYWORDS = set(
    "abstract assert boolean break byte case catch char class const continue default do "
    "double else enum extends final finally float for goto if implements import instanceof "
    "int interface long native new package private protected public return short static "
    "strictfp super switch synchronized this throw throws transient try void volatile while "
    "record sealed permits var yield true false null _".split()
)
JAVA_TYPES = {"Boolean", "Double", "double[]", "Instant", "Integer", "Long", "String"}
RECORD_RESERVED_FIELDS = {
    "clone", "finalize", "getClass", "hashCode", "notify", "notifyAll", "toString", "wait"
}
WINDOWS_RESERVED_NAMES = {"CON", "PRN", "AUX", "NUL"} | {
    f"{prefix}{number}" for prefix in ("COM", "LPT") for number in range(1, 10)
}
JAVA_IDENTIFIER = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*")


def camel_case(value: str) -> str:
    if not isinstance(value, str):
        raise ValueError("Column name must be a string")
    parts = [part for part in value.split("_") if part]
    if not parts:
        raise ValueError("Column name must contain a Java field name")
    result = (parts[0][:1].lower() + parts[0][1:]) + "".join(
        part[:1].upper() + part[1:] for part in parts[1:]
    )
    return f"field{result}" if result[:1].isdigit() else result


def require_class_name(value: str) -> None:
    if (not isinstance(value, str) or not JAVA_IDENTIFIER.fullmatch(value)
            or value in JAVA_KEYWORDS or value.upper() in WINDOWS_RESERVED_NAMES):
        raise ValueError(f"Invalid Java class name: {value!r}")


def java_source(package: str, class_name: str, obj: dict) -> str:
    require_class_name(class_name)
    name = obj.get("name")
    if (not isinstance(name, str) or not name or "*/" in name or "\\" in name
            or any(ord(character) < 32 for character in name)):
        raise ValueError("Object name cannot be embedded safely in Java documentation")
    columns = obj.get("columns")
    if not isinstance(columns, list) or not columns:
        raise ValueError(f"No output columns found for {name}")
    components = []
    seen = set()
    for column in columns:
        if not isinstance(column, dict):
            raise ValueError(f"Invalid column in {name}")
        field_name = camel_case(column.get("name"))
        if (not JAVA_IDENTIFIER.fullmatch(field_name) or field_name in JAVA_KEYWORDS
                or field_name in RECORD_RESERVED_FIELDS):
            raise ValueError(f"Invalid Java field {name}.{column.get('name')} -> {field_name}")
        if field_name in seen:
            raise ValueError(f"Field name collision in {name}: {field_name}")
        seen.add(field_name)
        java_type = column.get("javaType")
        if not isinstance(java_type, str) or java_type not in JAVA_TYPES:
            raise ValueError(f"No Java type mapping for {name}.{column.get('name')}: {java_type!r}")
        components.append(f"        {java_type} {field_name}")
    fields = ",\n".join(components)
    return (
        f"package {package};\n\n"
        "import java.time.Instant;\n\n"
        f"{MARKER}\n"
        f"/** Schema projection for QuestDB object `{name}`; source snapshot {obj['snapshotDate']}. */\n"
        f"public record {class_name}(\n{fields}) {{}}\n"
    )


@dataclass(frozen=True)
class GenerationPlan:
    root: Path
    outputs: tuple[tuple[Path, str], ...]
    stale: tuple[Path, ...]


def require_contained(path: Path, root: Path) -> None:
    if not path.resolve().is_relative_to(root):
        raise ValueError(f"Generated path escapes output root: {path}")
    # The explicitly selected root is resolved first; linked descendants are rejected.
    for candidate in (path, *path.parents):
        if candidate == root:
            break
        if candidate.is_symlink() or getattr(candidate, "is_junction", lambda: False)():
            raise ValueError(f"Generated path uses a linked descendant: {candidate}")


def is_generated(path: Path) -> bool:
    return MARKER in path.read_text(encoding="utf-8").splitlines()


def validate_plan_paths(plan: GenerationPlan) -> None:
    if plan.root.exists() and not plan.root.is_dir():
        raise ValueError(f"Output root is not a directory: {plan.root}")
    for path, _ in plan.outputs:
        require_contained(path, plan.root)
        if path.parent.exists() and not path.parent.is_dir():
            raise ValueError(f"Output package is not a directory: {path.parent}")
        if path.exists() and (not path.is_file() or not is_generated(path)):
            raise ValueError(f"Refusing to overwrite a non-generated file: {path}")
    for path in plan.stale:
        require_contained(path, plan.root)
        if not path.is_file() or not is_generated(path):
            raise ValueError(f"Refusing to remove a non-generated file: {path}")


def plan_generation(catalog: dict, output_root: Path) -> GenerationPlan:
    if not isinstance(catalog, dict) or not isinstance(catalog.get("objects"), list):
        raise ValueError("Catalog must contain an objects list")
    snapshot = catalog.get("snapshotDate")
    if not isinstance(snapshot, str) or date.fromisoformat(snapshot).isoformat() != snapshot:
        raise ValueError("Catalog snapshotDate must be an ISO calendar date")
    root = output_root.resolve()
    outputs = []
    names = set()
    for original in catalog["objects"]:
        if not isinstance(original, dict):
            raise ValueError("Catalog object must be a mapping")
        class_name = original.get("domainClass")
        if not class_name:
            continue
        require_class_name(class_name)
        kind = original.get("objectType")
        if not isinstance(kind, str) or kind not in PACKAGE_BY_TYPE:
            raise ValueError(f"Unsupported object type for {class_name}: {kind!r}")
        folder, _ = PACKAGE_BY_TYPE[kind]
        relative = Path(folder) / f"{class_name}.java"
        # Case-fold on every platform so a catalog cannot overwrite files on Windows.
        identity = relative.as_posix().casefold()
        if identity in names:
            raise ValueError(f"Duplicate generated class: {relative}")
        names.add(identity)
        obj = dict(original, snapshotDate=snapshot)
        source = java_source(f"com.zoutrankil.data.domain.{folder}", class_name, obj)
        outputs.append((root / relative, source))

    stale = []
    for folder, _ in PACKAGE_BY_TYPE.values():
        package_dir = root / folder
        require_contained(package_dir, root)
        if package_dir.exists() and not package_dir.is_dir():
            raise ValueError(f"Output package is not a directory: {package_dir}")
        if not package_dir.exists():
            continue
        for path in sorted(package_dir.glob("*.java")):
            require_contained(path, root)
            if path.is_file() and path.relative_to(root).as_posix().casefold() not in names and is_generated(path):
                stale.append(path)
    plan = GenerationPlan(root, tuple(sorted(outputs)), tuple(stale))
    validate_plan_paths(plan)
    return plan


def apply_generation(plan: GenerationPlan) -> None:
    # Recheck every target together before the first filesystem mutation.
    validate_plan_paths(plan)
    for path, source in plan.outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(source.encode("utf-8"))
    for path in plan.stale:
        path.unlink()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--catalog", type=Path,
        default=Path("schema-export/questdb-qdb-2026-09-28/domain-catalog.json"),
    )
    parser.add_argument(
        "--output-root", type=Path, default=PACKAGE_ROOT,
        help="Domain directory containing table, view and materializedview packages",
    )
    args = parser.parse_args(argv)
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    plan = plan_generation(catalog, args.output_root)
    apply_generation(plan)
    print(f"Generated {len(plan.outputs)} schema projection records from {args.catalog}")


if __name__ == "__main__":
    main()
