import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.zoutrankil.questdbwithdata.domain.JobDefinitionJson;
import com.zoutrankil.questdbwithdata.repository.SyncRunLedger;
import com.zoutrankil.questdbwithdata.service.StaticTargetIdentity;
import java.math.BigDecimal;
import java.nio.file.*;
import java.security.MessageDigest;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;

/** Independent raw-receipt-to-QuestDB oracle; it deliberately does not call D029 source, mapper or write port. */
public final class MarginDetailIndependentReadback {
    private static final int ROW_CAP=6_000,MAX_EVIDENCE_BYTES=32*1024*1024;
    private static final List<String> FIELDS=List.of("trade_date","ts_code","name","rzye","rzmre","rzche","rqye","rqyl","rqchl","rqmcl","rzrqye");
    private static final List<String> NUMERIC=List.of("rzye","rzmre","rzche","rqye","rqyl","rqchl","rqmcl","rzrqye");
    private static final long MICROS_PER_DAY=86_400_000_000L;
    private MarginDetailIndependentReadback(){}

    public static Map<String,Object> verify(JdbcTemplate jdbc,Path ledgerPath,String table,String runId)throws Exception{
        Objects.requireNonNull(jdbc);Objects.requireNonNull(ledgerPath);if(table==null||!table.matches("java_d029_margin_detail_[A-Za-z0-9_]{1,80}")
                ||runId==null||!runId.matches("[A-Za-z0-9_.:-]{1,128}")||runId.contains(".."))throw new IllegalArgumentException("Explicit isolated D029 table and bounded run ID required");
        var ledger=SyncRunLedger.openReadOnly(ledgerPath);var run=ledger.getRun(runId);var runState=ledger.get(runId);if(!"data.margin_detail".equals(run.jobId())||run.jobVersion()!=1||!runState.state().equals(com.zoutrankil.questdbwithdata.domain.SyncRunState.VERIFIED))throw new IllegalStateException("Independent D029 readback requires a VERIFIED D029 run");
        JsonNode frozen=JobDefinitionJson.mapper().readTree(run.frozenJson());if(!"INCREMENTAL".equals(frozen.path("mode").asText())&& !"BACKFILL".equals(frozen.path("mode").asText()))throw new IllegalStateException("Unsupported D029 verification mode");
        LocalDate from=LocalDate.parse(frozen.path("from").asText()),to=LocalDate.parse(frozen.path("to").asText());if(to.isBefore(from)||java.time.temporal.ChronoUnit.DAYS.between(from,to)+1>14)throw new IllegalStateException("D029 verification window exceeds bound");
        if(!run.targetId().equals(frozen.path("parameters").path("targetId").asText()))throw new IllegalStateException("D029 run target differs from its frozen request");
        var target=jdbc.queryForList("SELECT id,directoryName FROM tables() WHERE table_name=?",table);if(target.size()!=1||!(target.getFirst().get("id") instanceof Number tableId)
                ||!(target.getFirst().get("directoryName") instanceof String directory)||!run.targetId().equals(StaticTargetIdentity.identify(jdbc,table,tableId.longValue(),directory)))throw new IllegalStateException("D029 current physical table identity differs from frozen run");
        Path runRoot=ledgerPath.toAbsolutePath().normalize().getParent().resolve("sync-evidence").resolve(runId).toRealPath();Path sourceRoot=runRoot.resolve("source").toRealPath();
        var dates=decodeDates(frozen.path("parameters").path("trade_dates").asText(),from,to);var slices=ledger.entries(runId,null,1000).stream().filter(e->e.kind()==SyncRunLedger.Kind.SLICE).toList();if(slices.size()!=dates.size())throw new IllegalStateException("D029 run does not contain exactly one source slice per frozen date");
        var expectedByDate=new LinkedHashMap<LocalDate,Map<String,Map<String,Object>>>();var receiptRefs=new ArrayList<Map<String,Object>>();int totalSource=0;
        for(var slice:slices){if(!slice.state().equals(com.zoutrankil.questdbwithdata.domain.SyncRunState.VERIFIED))throw new IllegalStateException("D029 source slice is not VERIFIED");var events=ledger.events(slice.id(),-1,100).stream().filter(e->e.state()==com.zoutrankil.questdbwithdata.domain.SyncRunState.FETCHED).toList();if(events.size()!=1)throw new IllegalStateException("D029 source slice lacks one FETCHED event");
            JsonNode event=JobDefinitionJson.mapper().readTree(events.getFirst().payloadJson());String cursor=event.path("cursor").asText();if(!cursor.matches("[0-9]{8}"))throw new IllegalStateException("D029 cursor must be YYYYMMDD");LocalDate date=LocalDate.parse(cursor,DateTimeFormatter.BASIC_ISO_DATE);if(!dates.contains(date))throw new IllegalStateException("D029 receipt outside frozen date list");
            String evidence=event.path("responseEvidence").asText(),fingerprint=event.path("sourceFingerprint").asText();Path receipt=Path.of(evidence).toAbsolutePath().normalize();if(!receipt.startsWith(sourceRoot)||Files.isSymbolicLink(receipt)||!Files.isRegularFile(receipt,LinkOption.NOFOLLOW_LINKS)||!receipt.toRealPath().startsWith(sourceRoot)||Files.size(receipt)>MAX_EVIDENCE_BYTES)throw new IllegalStateException("D029 source receipt outside bounded run/source evidence");
            byte[] bytes=Files.readAllBytes(receipt);if(!sha(bytes).equals(fingerprint))throw new IllegalStateException("D029 FETCHED fingerprint differs from raw receipt SHA");JsonNode proof=JobDefinitionJson.mapper().readTree(bytes);String basic=date.format(DateTimeFormatter.BASIC_ISO_DATE);
            if(!"tushare".equals(proof.path("sourceKind").asText())||!"margin_detail".equals(proof.path("endpoint").asText())||proof.path("sourceContractVersion").asInt(-1)!=1||!proof.path("sourceComplete").asBoolean(false)
                    ||!date.toString().equals(proof.path("tradeDate").asText())||proof.path("apiMaximumRows").asInt(-1)!=ROW_CAP||!JobDefinitionJson.mapper().valueToTree(FIELDS).equals(proof.path("fields"))
                    ||!basic.equals(proof.path("parameters").path("trade_date").asText())||!proof.path("rawRows").isArray()||proof.path("rawRows").size()!=event.path("returnedRows").asInt(-1)||proof.path("rawRows").size()>=ROW_CAP)
                throw new IllegalStateException("D029 raw receipt violates frozen endpoint/date/fields/cap contract");
            List<Map<String,JsonNode>> raw=JobDefinitionJson.mapper().convertValue(proof.path("rawRows"),new TypeReference<>(){});var expected=new LinkedHashMap<String,Map<String,Object>>();int footerCount=0;
            for(var row:raw){if(!row.keySet().equals(new HashSet<>(FIELDS))||!basic.equals(text(row,"trade_date")))throw new IllegalStateException("D029 raw row fields/date differ from frozen contract");String code=text(row,"ts_code");boolean footer=code.equals(footerLabel(date));if(footer){footerCount++;for(String field:NUMERIC)if(row.get(field)!=null&&!row.get(field).isNull())throw new IllegalStateException("D029 date footer contains values");continue;}
                if(!code.matches("[0-9]{6}\\.(SH|SZ|BJ)"))throw new IllegalStateException("D029 raw key has invalid exchange suffix");JsonNode name=row.get("name");if(name!=null&&!name.isNull()&&!name.isTextual())throw new IllegalStateException("D029 raw name is not text/null");
                var normalized=new LinkedHashMap<String,Object>();normalized.put("trade_date",date);normalized.put("ts_code",code);normalized.put("name",name==null||name.isNull()?null:name.textValue());for(String field:NUMERIC){JsonNode v=row.get(field);Double number=v==null||v.isNull()?null:finite(v,field);if(Set.of("rzye","rzmre").contains(field)&&(number==null||number<0))throw new IllegalStateException("D029 required margin balance invalid");if(number!=null&&Set.of("rqye","rqyl","rqmcl","rzrqye").contains(field)&&number<0)throw new IllegalStateException("D029 nonnegative source value invalid");normalized.put(field,number);}
                String key=basic+"|"+code;if(expected.putIfAbsent(key,Collections.unmodifiableMap(new LinkedHashMap<>(normalized)))!=null)throw new IllegalStateException("D029 duplicate raw source key");}
            if(footerCount!=proof.path("excludedDateFooters").asInt(-1)||expected.size()!=proof.path("normalizedRows").asInt(-1)||expected.isEmpty()||expected.size()!=event.path("returnedRows").asInt(-1)-footerCount)throw new IllegalStateException("D029 normalized/source footer totals are inconsistent");
            var sortedRaw=new ArrayList<>(raw);sortedRaw.sort(Comparator.comparing((Map<String,JsonNode> r)->text(r,"ts_code")).thenComparing(r->text(r,"trade_date")));if(!JobDefinitionJson.mapper().valueToTree(sortedRaw).equals(JobDefinitionJson.mapper().valueToTree(raw)))throw new IllegalStateException("D029 raw rows are not stable-sorted");
            if(expectedByDate.putIfAbsent(date,Map.copyOf(expected))!=null)throw new IllegalStateException("D029 duplicate trade-date source receipt");totalSource=Math.addExact(totalSource,expected.size());receiptRefs.add(Map.of("tradeDate",date.toString(),"rows",expected.size(),"sourceFingerprint",fingerprint,"responseEvidence",receipt.toString()));}
        if(!expectedByDate.keySet().equals(new HashSet<>(dates)))throw new IllegalStateException("D029 receipt date set differs from frozen trading dates");
        var json=JobDefinitionJson.mapper();Path manifest=runRoot.resolve("complete-window.json");if(!Files.isRegularFile(manifest,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(manifest)||Files.size(manifest)>1024*1024)throw new IllegalStateException("D029 completion manifest absent/oversized");JsonNode completion=json.readTree(Files.readAllBytes(manifest));
        if(!"margin_detail".equals(completion.path("dataset").asText())||!"margin_detail".equals(completion.path("endpoint").asText())||!run.targetId().equals(completion.path("targetId").asText())
                ||!frozen.path("mode").asText().equals(completion.path("mode").asText())||!from.toString().equals(completion.path("fromInclusive").asText())||!to.toString().equals(completion.path("toInclusive").asText())
                ||!json.valueToTree(dates).equals(completion.path("tradeDates"))||completion.path("completedDateSlices").asInt(-1)!=dates.size()
                ||!completion.path("sourceComplete").asBoolean(false)||!completion.path("complete").asBoolean(false)||completion.path("sourceRows").asInt(-1)!=totalSource
                ||completion.path("returnedRows").asInt(-1)!=totalSource||!json.valueToTree(receiptRefs).equals(completion.path("sourceReceipts")))throw new IllegalStateException("D029 completion manifest differs from source receipts");

        var physical=new JdbcTemplate(jdbc.getDataSource());physical.setQueryTimeout(30);physical.setMaxRows(dates.size()*ROW_CAP+1);long actualRows=0,matched=0,duplicates=0,missing=0,extras=0,mismatched=0;var samples=new ArrayList<String>();
        for(LocalDate date:dates){String basic=date.format(DateTimeFormatter.BASIC_ISO_DATE);long micros=Math.multiplyExact(date.toEpochDay(),MICROS_PER_DAY);String sql="SELECT ts_code,cast(trade_date AS long) AS trade_date_micros,name,rzye,rzmre,rzche,rqye,rqyl,rqchl,rqmcl,rzrqye FROM \""+table+"\" WHERE trade_date>=cast(? AS TIMESTAMP) AND trade_date<cast(? AS TIMESTAMP) ORDER BY ts_code LIMIT "+(ROW_CAP+1);
            List<Map<String,Object>> rows=physical.query(sql,rs->{var found=new ArrayList<Map<String,Object>>();while(rs.next()){var row=new LinkedHashMap<String,Object>();row.put("ts_code",rs.getString("ts_code"));Object rawMicros=rs.getObject("trade_date_micros");if(!(rawMicros instanceof Number n))throw new SQLException("D029 physical timestamp missing");long value=n.longValue();if(value%MICROS_PER_DAY!=0)throw new SQLException("D029 physical timestamp not UTC midnight");row.put("trade_date",LocalDate.ofEpochDay(value/MICROS_PER_DAY));row.put("name",rs.getString("name"));for(String field:NUMERIC){Object numeric=rs.getObject(field);row.put(field,numeric==null?null:((Number)numeric).doubleValue());}found.add(Collections.unmodifiableMap(new LinkedHashMap<>(row)));}return found;},micros,Math.multiplyExact(date.plusDays(1).toEpochDay(),MICROS_PER_DAY));
            if(rows.size()>ROW_CAP)throw new IllegalStateException("D029 physical date exceeds readback cap");actualRows+=rows.size();var actual=new HashMap<String,Map<String,Object>>();for(var row:rows){String code=(String)row.get("ts_code");if(code==null||!code.matches("[0-9]{6}\\.(SH|SZ|BJ)"))throw new IllegalStateException("D029 physical row has an invalid natural key");String key=basic+"|"+code;if(actual.putIfAbsent(key,row)!=null){duplicates++;if(samples.size()<10)samples.add("duplicate:"+key);}}
            var expected=expectedByDate.get(date);for(var entry:expected.entrySet()){Map<String,Object> observed=actual.remove(entry.getKey());if(observed==null){missing++;if(samples.size()<10)samples.add("missing:"+entry.getKey());}else if(!entry.getValue().equals(observed)){mismatched++;if(samples.size()<10)samples.add("value:"+entry.getKey());}else matched++;}
            extras+=actual.size();if(samples.size()<10)actual.keySet().stream().limit(10-samples.size()).forEach(k->samples.add("extra:"+k));}
        String status=matched==totalSource&&actualRows==totalSource&&duplicates==0&&missing==0&&extras==0&&mismatched==0?"MATCHED":"MISMATCH";
        return Map.ofEntries(Map.entry("status",status),Map.entry("taskId","D029"),Map.entry("runId",runId),Map.entry("table",table),Map.entry("requestFrom",from.toString()),Map.entry("requestTo",to.toString()),
                Map.entry("sourceRows",totalSource),Map.entry("actualRows",actualRows),Map.entry("matchedRows",matched),Map.entry("missingKeys",missing),Map.entry("extraKeys",extras),Map.entry("duplicateTargetKeys",duplicates),Map.entry("mismatchedValues",mismatched),Map.entry("samples",List.copyOf(samples)),Map.entry("fields",FIELDS));
    }
    private static List<LocalDate> decodeDates(String text,LocalDate from,LocalDate to){var dates=Arrays.stream(text.split(",",-1)).map(value->{if(!value.matches("[0-9]{8}"))throw new IllegalStateException("D029 invalid frozen date");return LocalDate.parse(value,DateTimeFormatter.BASIC_ISO_DATE);}).toList();if(dates.isEmpty()||dates.size()>14||dates.stream().distinct().count()!=dates.size()||!dates.equals(dates.stream().sorted().toList())||dates.stream().anyMatch(d->d.isBefore(from)||d.isAfter(to)))throw new IllegalStateException("D029 invalid frozen date set");return dates;}
    private static String footerLabel(LocalDate date){return "日期："+date+".BJ";}
    private static String text(Map<String,JsonNode> row,String field){JsonNode value=row.get(field);return value==null||value.isNull()?"":value.asText();}
    private static Double finite(JsonNode value,String field){if(!value.isNumber()&&!value.isTextual())throw new IllegalStateException("D029 non-scalar numeric field "+field);double number=new BigDecimal(value.asText().strip()).doubleValue();if(!Double.isFinite(number))throw new IllegalStateException("D029 non-finite numeric field "+field);return number;}
    private static String sha(byte[] bytes)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}
}
